load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["kv-coverage-collector.go"],
    importpath = "kubevirt.io/kubevirt/cmd/kv-coverage-collector",
    visibility = ["//visibility:private"],
    deps = [
        "//pkg/coveragecollector:go_default_library",
        "//staging/src/kubevirt.io/client-go/log:go_default_library",
    ],
)

go_binary(
    name = "kv-coverage-collector",
    embed = [":go_default_library"],
    visibility = ["//visibility:public"],
)
