/*
Copyright The KubeVirt Authors.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
	v1beta1 "kubevirt.io/client-go/kubevirt/typed/instancetype/v1beta1"
)

type FakeInstancetypeV1beta1 struct {
	*testing.Fake
}

func (c *FakeInstancetypeV1beta1) VirtualMachineClusterInstancetypes() v1beta1.VirtualMachineClusterInstancetypeInterface {
	return newFakeVirtualMachineClusterInstancetypes(c)
}

func (c *FakeInstancetypeV1beta1) VirtualMachineClusterPreferences() v1beta1.VirtualMachineClusterPreferenceInterface {
	return newFakeVirtualMachineClusterPreferences(c)
}

func (c *FakeInstancetypeV1beta1) VirtualMachineInstancetypes(namespace string) v1beta1.VirtualMachineInstancetypeInterface {
	return newFakeVirtualMachineInstancetypes(c, namespace)
}

func (c *FakeInstancetypeV1beta1) VirtualMachinePreferences(namespace string) v1beta1.VirtualMachinePreferenceInterface {
	return newFakeVirtualMachinePreferences(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeInstancetypeV1beta1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
