/*
Copyright The KubeVirt Authors.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	scheme "kubevirt.io/client-go/containerizeddataimporter/scheme"
	corev1beta1 "kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1"
)

// CDIsGetter has a method to return a CDIInterface.
// A group's client should implement this interface.
type CDIsGetter interface {
	CDIs() CDIInterface
}

// CDIInterface has methods to work with CDI resources.
type CDIInterface interface {
	Create(ctx context.Context, cDI *corev1beta1.CDI, opts v1.CreateOptions) (*corev1beta1.CDI, error)
	Update(ctx context.Context, cDI *corev1beta1.CDI, opts v1.UpdateOptions) (*corev1beta1.CDI, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, cDI *corev1beta1.CDI, opts v1.UpdateOptions) (*corev1beta1.CDI, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1beta1.CDI, error)
	List(ctx context.Context, opts v1.ListOptions) (*corev1beta1.CDIList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corev1beta1.CDI, err error)
	CDIExpansion
}

// cDIs implements CDIInterface
type cDIs struct {
	*gentype.ClientWithList[*corev1beta1.CDI, *corev1beta1.CDIList]
}

// newCDIs returns a CDIs
func newCDIs(c *CdiV1beta1Client) *cDIs {
	return &cDIs{
		gentype.NewClientWithList[*corev1beta1.CDI, *corev1beta1.CDIList](
			"cdis",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *corev1beta1.CDI { return &corev1beta1.CDI{} },
			func() *corev1beta1.CDIList { return &corev1beta1.CDIList{} },
		),
	}
}
