apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    kubevirt.io: ""
    {{- include "kubevirt-operator.labels" . | nindent 4 }}
  name: {{ include "kubevirt-operator.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubevirt-operator.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubevirt-operator.name" . }}
  namespace: {{ .Release.Namespace }}
