apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    kubevirt.io: ""
    {{- include "kubevirt-operator.labels" . | nindent 4 }}
  name: {{ include "kubevirt-operator.name" . }}
  namespace: {{ .Release.Namespace }}
