/*
This file is part of the KubeVirt project

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Copyright The KubeVirt Authors.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	backupv1alpha1 "kubevirt.io/api/backup/v1alpha1"
)

// VirtualMachineBackupSpecApplyConfiguration represents a declarative configuration of the VirtualMachineBackupSpec type for use
// with apply.
type VirtualMachineBackupSpecApplyConfiguration struct {
	Source          *v1.TypedLocalObjectReference `json:"source,omitempty"`
	Mode            *backupv1alpha1.BackupMode    `json:"mode,omitempty"`
	PvcName         *string                       `json:"pvcName,omitempty"`
	SkipQuiesce     *bool                         `json:"skipQuiesce,omitempty"`
	ForceFullBackup *bool                         `json:"forceFullBackup,omitempty"`
	TokenSecretRef  *string                       `json:"tokenSecretRef,omitempty"`
	TTLDuration     *metav1.Duration              `json:"ttlDuration,omitempty"`
}

// VirtualMachineBackupSpecApplyConfiguration constructs a declarative configuration of the VirtualMachineBackupSpec type for use with
// apply.
func VirtualMachineBackupSpec() *VirtualMachineBackupSpecApplyConfiguration {
	return &VirtualMachineBackupSpecApplyConfiguration{}
}

// WithSource sets the Source field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Source field is set to the value of the last call.
func (b *VirtualMachineBackupSpecApplyConfiguration) WithSource(value v1.TypedLocalObjectReference) *VirtualMachineBackupSpecApplyConfiguration {
	b.Source = &value
	return b
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *VirtualMachineBackupSpecApplyConfiguration) WithMode(value backupv1alpha1.BackupMode) *VirtualMachineBackupSpecApplyConfiguration {
	b.Mode = &value
	return b
}

// WithPvcName sets the PvcName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PvcName field is set to the value of the last call.
func (b *VirtualMachineBackupSpecApplyConfiguration) WithPvcName(value string) *VirtualMachineBackupSpecApplyConfiguration {
	b.PvcName = &value
	return b
}

// WithSkipQuiesce sets the SkipQuiesce field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SkipQuiesce field is set to the value of the last call.
func (b *VirtualMachineBackupSpecApplyConfiguration) WithSkipQuiesce(value bool) *VirtualMachineBackupSpecApplyConfiguration {
	b.SkipQuiesce = &value
	return b
}

// WithForceFullBackup sets the ForceFullBackup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ForceFullBackup field is set to the value of the last call.
func (b *VirtualMachineBackupSpecApplyConfiguration) WithForceFullBackup(value bool) *VirtualMachineBackupSpecApplyConfiguration {
	b.ForceFullBackup = &value
	return b
}

// WithTokenSecretRef sets the TokenSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TokenSecretRef field is set to the value of the last call.
func (b *VirtualMachineBackupSpecApplyConfiguration) WithTokenSecretRef(value string) *VirtualMachineBackupSpecApplyConfiguration {
	b.TokenSecretRef = &value
	return b
}

// WithTTLDuration sets the TTLDuration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TTLDuration field is set to the value of the last call.
func (b *VirtualMachineBackupSpecApplyConfiguration) WithTTLDuration(value metav1.Duration) *VirtualMachineBackupSpecApplyConfiguration {
	b.TTLDuration = &value
	return b
}
