/*
This file is part of the KubeVirt project

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Copyright The KubeVirt Authors.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// VirtualMachineBackupTrackerStatusApplyConfiguration represents a declarative configuration of the VirtualMachineBackupTrackerStatus type for use
// with apply.
type VirtualMachineBackupTrackerStatusApplyConfiguration struct {
	LatestCheckpoint               *BackupCheckpointApplyConfiguration `json:"latestCheckpoint,omitempty"`
	CheckpointRedefinitionRequired *bool                               `json:"checkpointRedefinitionRequired,omitempty"`
}

// VirtualMachineBackupTrackerStatusApplyConfiguration constructs a declarative configuration of the VirtualMachineBackupTrackerStatus type for use with
// apply.
func VirtualMachineBackupTrackerStatus() *VirtualMachineBackupTrackerStatusApplyConfiguration {
	return &VirtualMachineBackupTrackerStatusApplyConfiguration{}
}

// WithLatestCheckpoint sets the LatestCheckpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LatestCheckpoint field is set to the value of the last call.
func (b *VirtualMachineBackupTrackerStatusApplyConfiguration) WithLatestCheckpoint(value *BackupCheckpointApplyConfiguration) *VirtualMachineBackupTrackerStatusApplyConfiguration {
	b.LatestCheckpoint = value
	return b
}

// WithCheckpointRedefinitionRequired sets the CheckpointRedefinitionRequired field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CheckpointRedefinitionRequired field is set to the value of the last call.
func (b *VirtualMachineBackupTrackerStatusApplyConfiguration) WithCheckpointRedefinitionRequired(value bool) *VirtualMachineBackupTrackerStatusApplyConfiguration {
	b.CheckpointRedefinitionRequired = &value
	return b
}
