/*
This file is part of the KubeVirt project

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Copyright The KubeVirt Authors.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// VirtualMachinePoolSelectorsApplyConfiguration represents a declarative configuration of the VirtualMachinePoolSelectors type for use
// with apply.
type VirtualMachinePoolSelectorsApplyConfiguration struct {
	LabelSelector                  *v1.LabelSelectorApplyConfiguration `json:"labelSelector,omitempty"`
	NodeSelectorRequirementMatcher *[]corev1.NodeSelectorRequirement   `json:"nodeSelectorRequirementMatcher,omitempty"`
}

// VirtualMachinePoolSelectorsApplyConfiguration constructs a declarative configuration of the VirtualMachinePoolSelectors type for use with
// apply.
func VirtualMachinePoolSelectors() *VirtualMachinePoolSelectorsApplyConfiguration {
	return &VirtualMachinePoolSelectorsApplyConfiguration{}
}

// WithLabelSelector sets the LabelSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LabelSelector field is set to the value of the last call.
func (b *VirtualMachinePoolSelectorsApplyConfiguration) WithLabelSelector(value *v1.LabelSelectorApplyConfiguration) *VirtualMachinePoolSelectorsApplyConfiguration {
	b.LabelSelector = value
	return b
}

// WithNodeSelectorRequirementMatcher sets the NodeSelectorRequirementMatcher field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeSelectorRequirementMatcher field is set to the value of the last call.
func (b *VirtualMachinePoolSelectorsApplyConfiguration) WithNodeSelectorRequirementMatcher(value []corev1.NodeSelectorRequirement) *VirtualMachinePoolSelectorsApplyConfiguration {
	b.NodeSelectorRequirementMatcher = &value
	return b
}
