ARG BUILDER_IMAGE
FROM $BUILDER_IMAGE as builder
WORKDIR /workspace

RUN --mount=type=bind,rw,target=. \
    hack/build-mariner-based-imgs/slim-build.sh /build \
      cmd/virt-operator \
      cmd/virtctl \
      tools/csv-generator


FROM mcr.microsoft.com/cbl-mariner/base/core:2.0

RUN tdnf install -y mariner-repos-preview
RUN tdnf -y install \
  ca-certificates \
  shadow-utils \
  tar \
  && tdnf clean all

RUN  adduser --system --no-create-home -u 101 virt-operator
USER 101

COPY --from=builder /build/_out/cmd/virtctl/virtctl /usr/bin/
COPY --from=builder /build/_out/cmd/virt-operator/virt-operator /usr/bin/
COPY --from=builder /build/_out/cmd/csv-generator/csv-generator /usr/bin/

RUN ls /usr/bin/virt-operator

ENTRYPOINT [ "/usr/bin/virt-operator" ]

