apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: vmi-ready
spec:
  resourceRef:
    apiGroup: kubevirt.io/v1
    kind: VirtualMachineInstance
  selector:
    matchExpressions:
      - key: '.metadata.deletionTimestamp'
        operator: 'DoesNotExist'
      - key: '.status.phase'
        operator: 'NotIn'
        values:
          - 'Running'
      - key: '.spec.nodeSelector.type'
        operator: 'In'
        values:
          - 'kwok'
  next:
    statusTemplate: |
      {{ $now := Now }}
      activePods:
      {{ YAML .status.activePods 1 }}
      conditions:
      - type: Ready
        status: "True"
        lastTransitionTime: {{ $now }}
      guestOSInfo: {}
      launcherContainerImageVersion: {{ .status.launcherContainerImageVersion }}
      memory:
      {{ YAML .status.memory 1 }}
      migrationTransport: Unix
      nodeName: {{ .status.nodeName }}
      phase: Running
      phaseTransitionTimestamps:
      {{ YAML .status.phaseTransitionTimestamps 0 }}
      - phase: Running
        phaseTransitionTimestamp: {{ $now }}
      qosClass: {{ .status.qosClass }}
      runtimeUser: {{ .status.runtimeUser }}
      volumeStatus:
      {{ YAML .status.volumeStatus 1 }}
    statusSubresource: ""
    statusPatchAs:
      username: system:serviceaccount:kubevirt:kubevirt-controller