apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: vmi-delete
spec:
  resourceRef:
    apiGroup: kubevirt.io/v1
    kind: VirtualMachineInstance
  selector:
    matchExpressions:
      - key: '.metadata.deletionTimestamp'
        operator: 'Exists'
  next:
    finalizers:
      empty: true
    delete: true