load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "addvolume.go",
        "backup.go",
        "console.go",
        "dummy.go",
        "evacuate.go",
        "filesystemlist.go",
        "freeze.go",
        "guestosinfo.go",
        "objectgraph.go",
        "pause.go",
        "portforward.go",
        "redefinecheckpoint.go",
        "removevolume.go",
        "reset.go",
        "sev.go",
        "softreboot.go",
        "storage.go",
        "unfreeze.go",
        "unpause.go",
        "usbredir.go",
        "userlist.go",
        "vnc.go",
        "vsock.go",
    ],
    importpath = "kubevirt.io/kubevirt/pkg/virt-api/apiserver/storage/virtualmachineinstance",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/virt-api/apiserver/storage/evacuate:go_default_library",
        "//pkg/virt-api/apiserver/storage/objectgraph:go_default_library",
        "//pkg/virt-api/apiserver/storage/virtualmachineinstance/backup:go_default_library",
        "//pkg/virt-api/apiserver/storage/virtualmachineinstance/console:go_default_library",
        "//pkg/virt-api/apiserver/storage/virtualmachineinstance/guestinfo:go_default_library",
        "//pkg/virt-api/apiserver/storage/virtualmachineinstance/lifecycle:go_default_library",
        "//pkg/virt-api/apiserver/storage/virtualmachineinstance/sev:go_default_library",
        "//pkg/virt-api/apiserver/storage/virtualmachineinstance/usbredir:go_default_library",
        "//pkg/virt-api/apiserver/storage/virtualmachineinstance/vnc:go_default_library",
        "//pkg/virt-api/apiserver/storage/virtualmachineinstance/vsock:go_default_library",
        "//pkg/virt-api/apiserver/storage/volumes:go_default_library",
        "//pkg/virt-api/definitions:go_default_library",
        "//pkg/virt-api/streaming:go_default_library",
        "//pkg/virt-config:go_default_library",
        "//staging/src/kubevirt.io/api/core/v1:go_default_library",
        "//staging/src/kubevirt.io/client-go/kubecli:go_default_library",
        "//staging/src/kubevirt.io/client-go/log:go_default_library",
        "//vendor/k8s.io/apimachinery/pkg/api/errors:go_default_library",
        "//vendor/k8s.io/apimachinery/pkg/runtime:go_default_library",
        "//vendor/k8s.io/apimachinery/pkg/util/yaml:go_default_library",
        "//vendor/k8s.io/apiserver/pkg/endpoints/request:go_default_library",
        "//vendor/k8s.io/apiserver/pkg/registry/rest:go_default_library",
    ],
)
