load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "driver.go",
        "hostpath.go",
    ],
    importpath = "kubevirt.io/kubevirt/cmd/test-helpers/dra-test-driver/pkg/driver",
    visibility = ["//visibility:public"],
    deps = [
        "//vendor/github.com/opencontainers/selinux/go-selinux:go_default_library",
        "//vendor/k8s.io/api/resource/v1:go_default_library",
        "//vendor/k8s.io/apimachinery/pkg/types:go_default_library",
        "//vendor/k8s.io/dynamic-resource-allocation/kubeletplugin:go_default_library",
        "//vendor/tags.cncf.io/container-device-interface/specs-go:go_default_library",
    ],
)
