apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachine
metadata:
  creationTimestamp: null
  labels:
    kubevirt.io/vm: vm-alpine-datavolume
  name: vm-alpine-datavolume
spec:
  running: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/vm: vm-alpine-datavolume
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: pvcdisk1
            volumeName: pvcvolume1
        machine:
          type: ""
        resources:
          requests:
            memory: 64M
      terminationGracePeriodSeconds: 0
      volumes:
      - dataVolume:
          pvc:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            selector:
              matchLabels:
                os: datavolume2
          source:
            http:
              url: http://cdi-http-import-server.kube-system/images/alpine.iso
        name: pvcvolume1
status: {}
