apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachineInstanceReplicaSet
metadata:
  creationTimestamp: null
  name: vmi-replicaset-cirros
spec:
  replicas: 3
  selector:
    matchLabels:
      kubevirt.io/vmReplicaSet: vmi-replicaset-cirros
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/vmReplicaSet: vmi-replicaset-cirros
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
            volumeName: registryvolume
        machine:
          type: ""
        resources:
          requests:
            memory: 64M
      terminationGracePeriodSeconds: 0
      volumes:
      - containerDisk:
          image: registry:5000/kubevirt/cirros-container-disk-demo:devel
        name: registryvolume
status: {}
