apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachineInstance
metadata:
  creationTimestamp: null
  labels:
    special: vmi-proxy
  name: vmi-proxy
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: registrydisk
        volumeName: registryvolume
      - disk:
          bus: virtio
        name: cloudinitdisk
        volumeName: cloudinitvolume
      interfaces:
      - name: testProxy
        ports:
        - name: http
          port: 80
          protocol: TCP
        proxy: {}
    machine:
      type: ""
    resources:
      requests:
        memory: 1024M
  networks:
  - name: testProxy
    pod: {}
  terminationGracePeriodSeconds: 0
  volumes:
  - name: registryvolume
    registryDisk:
      image: registry:5000/kubevirt/fedora-cloud-registry-disk-demo:devel
  - cloudInitNoCloud:
      userData: |-
        #!/bin/bash
        echo "fedora" |passwd fedora --stdin
        yum install -y nginx
        systemctl enable nginx
        systemctl start nginx
    name: cloudinitvolume
status: {}
