---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-tf-single-net
  name: vmi-tf-single-net
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      interfaces:
      - bridge: {}
        name: net1
    machine:
      type: ""
    resources:
      requests:
        memory: 1024M
  networks:
  - tungstenfabric:
      networkName: '{"domain":"default-domain", "project": "k8s-default","name":"net1"}'
    name: net1
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: registry:5000/kubevirt/fedora-cloud-container-disk-demo:devel
    name: containerdisk
  - cloudInitNoCloud:
      userData: |
        #!/bin/bash
        echo "fedora" | passwd fedora --stdin
        dhclient eth1
    name: cloudinitdisk
