---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-block-pvc
  name: vmi-block-pvc
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: blockpvcdisk
    machine:
      type: ""
    resources:
      requests:
        memory: 64M
  terminationGracePeriodSeconds: 0
  volumes:
  - name: blockpvcdisk
    persistentVolumeClaim:
      claimName: local-block-storage-cirros
