version: "2"

# golangci configuration

linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - mnd
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport # https://github.com/go-critic/go-critic/issues/845
        - ifElseChain
        - octalLiteral
        - paramTypeCombine
        - whyNoLint
        - wrapperFunc
      settings:
        hugeParam:
          sizeThreshold: 1024
        rangeValCopy:
          sizeThreshold: 1024
    gocyclo:
      min-complexity: 15
    mnd:
      checks:
        - argument
        - case
        - condition
        - return
      ignored-functions:
        - '^Eventually$'
        - '^EventuallyWithOffset$'
        - '^ExpectWithOffset$'
        - '^console\.ExpectBatch$'
        - '^console\.RunCommand$'
    govet:
      enable:
        - shadow
    lll:
      line-length: 140
    misspell:
      locale: US
    nolintlint:
      allow-unused: false
      require-explanation: false
      require-specific: false

issues:
  exclusions:
    rules:
      - text: 'SA1019: checks.SkipTestIfNoCPUManager'
        linters:
          - staticcheck

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - kubevirt.io/kubevirt
