ARG BUILDER_IMAGE=quay.io/kubevirt/builder:2606231619-4fe2cd536f

FROM ${BUILDER_IMAGE} AS builder

ARG BUILD_ARCH=amd64
ARG KUBEVIRT_VERSION

WORKDIR /workspace

COPY . .

RUN source /etc/profile.d/gimme.sh && \
    CGO_ENABLED=0 BIN_NAME=test-helpers KUBEVIRT_NO_BAZEL=true hack/build-go.sh install cmd/test-helpers/pod-mutator

RUN echo "nonroot-user:x:1001:1001:nonroot user:/home/nonroot-user:/sbin/nologin" > /tmp/passwd

FROM scratch

COPY --from=builder /workspace/_out/cmd/test-helpers/test-helpers /usr/bin/test-helpers
COPY --from=builder /tmp/passwd /etc/passwd

USER 1001

ENTRYPOINT ["/usr/bin/test-helpers"]
