ARG BUILDER_IMAGE=quay.io/kubevirt/builder:2606231619-4fe2cd536f

FROM --platform=linux/amd64 ${BUILDER_IMAGE} AS rpm-builder

ARG BUILD_ARCH=amd64
ARG CENTOS_STREAM_VERSION=9

WORKDIR /workspace
COPY . .

RUN export KUBEVIRT_BOOTSTRAPPING=true && \
    case ${BUILD_ARCH} in \
        amd64|x86_64) BAZEL_ARCH="x86_64" ;; \
        arm64|aarch64|crossbuild-aarch64) BAZEL_ARCH="aarch64" ;; \
        s390x|crossbuild-s390x) BAZEL_ARCH="s390x" ;; \
        *) echo "ERROR: Unsupported BUILD_ARCH: ${BUILD_ARCH}"; exit 1 ;; \
    esac && \
    bazel build --config=cs${CENTOS_STREAM_VERSION} //rpm:libvirt-devel_${BAZEL_ARCH} && \
    mkdir -p /devel && \
    tar -xf bazel-bin/rpm/libvirt-devel_${BAZEL_ARCH}_cs${CENTOS_STREAM_VERSION}.tar -C /devel --overwrite

FROM scratch

COPY --from=rpm-builder /devel/usr/lib64/pkgconfig /usr/lib64/pkgconfig
COPY --from=rpm-builder /devel/usr/include /usr/include
COPY --from=rpm-builder /devel/usr/lib64 /usr/lib64
