apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- multus.yaml
images:
- name: ghcr.io/k8snetworkplumbingwg/multus-cni
  newTag: v3.8
patchesJson6902:
- path: patch-args.yaml
  target:
    group: apps
    version: v1
    kind: DaemonSet
    name: kube-multus-ds
