/*
Copyright The KubeVirt Authors.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubevirt.io/client-go/kubevirt/typed/clone/v1alpha1"
)

type FakeCloneV1alpha1 struct {
	*testing.Fake
}

func (c *FakeCloneV1alpha1) VirtualMachineClones(namespace string) v1alpha1.VirtualMachineCloneInterface {
	return newFakeVirtualMachineClones(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeCloneV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
