/*
This file is part of the KubeVirt project

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Copyright The KubeVirt Authors.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"
	v1 "kubevirt.io/api/instancetype/v1"
	instancetypev1 "kubevirt.io/client-go/kubevirt/typed/instancetype/v1"
)

// fakeVirtualMachineClusterPreferences implements VirtualMachineClusterPreferenceInterface
type fakeVirtualMachineClusterPreferences struct {
	*gentype.FakeClientWithList[*v1.VirtualMachineClusterPreference, *v1.VirtualMachineClusterPreferenceList]
	Fake *FakeInstancetypeV1
}

func newFakeVirtualMachineClusterPreferences(fake *FakeInstancetypeV1) instancetypev1.VirtualMachineClusterPreferenceInterface {
	return &fakeVirtualMachineClusterPreferences{
		gentype.NewFakeClientWithList[*v1.VirtualMachineClusterPreference, *v1.VirtualMachineClusterPreferenceList](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("virtualmachineclusterpreferences"),
			v1.SchemeGroupVersion.WithKind("VirtualMachineClusterPreference"),
			func() *v1.VirtualMachineClusterPreference { return &v1.VirtualMachineClusterPreference{} },
			func() *v1.VirtualMachineClusterPreferenceList { return &v1.VirtualMachineClusterPreferenceList{} },
			func(dst, src *v1.VirtualMachineClusterPreferenceList) { dst.ListMeta = src.ListMeta },
			func(list *v1.VirtualMachineClusterPreferenceList) []*v1.VirtualMachineClusterPreference {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1.VirtualMachineClusterPreferenceList, items []*v1.VirtualMachineClusterPreference) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
