// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/handler-launcher-com/cmd/v1/cmd.proto

/*
Package v1 is a generated protocol buffer package.

It is generated from these files:

	pkg/handler-launcher-com/cmd/v1/cmd.proto

It has these top-level messages:

	QemuVersionResponse
	VMI
	CPU
	Sibling
	Pages
	Memory
	Cell
	Topology
	SMBios
	DiskInfo
	ClusterConfig
	InterfaceBindingMigration
	VirtualMachineOptions
	VMIRequest
	MigrationRequest
	ExecRequest
	EmptyRequest
	Response
	DomainResponse
	DomainStatsResponse
	GuestInfoResponse
	GuestUserListResponse
	GuestFilesystemsResponse
	ExecResponse
	GuestPingRequest
	GuestPingResponse
	FreezeRequest
	MemoryDumpRequest
	SEVInfoResponse
	LaunchMeasurementResponse
	InjectLaunchSecretRequest
*/
package v1

import (
	fmt "fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"

	context "golang.org/x/net/context"

	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type QemuVersionResponse struct {
	Response *Response `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
	Version  string    `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
}

func (m *QemuVersionResponse) Reset()                    { *m = QemuVersionResponse{} }
func (m *QemuVersionResponse) String() string            { return proto.CompactTextString(m) }
func (*QemuVersionResponse) ProtoMessage()               {}
func (*QemuVersionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *QemuVersionResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *QemuVersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type VMI struct {
	VmiJson []byte `protobuf:"bytes,1,opt,name=vmiJson,proto3" json:"vmiJson,omitempty"`
}

func (m *VMI) Reset()                    { *m = VMI{} }
func (m *VMI) String() string            { return proto.CompactTextString(m) }
func (*VMI) ProtoMessage()               {}
func (*VMI) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *VMI) GetVmiJson() []byte {
	if m != nil {
		return m.VmiJson
	}
	return nil
}

type CPU struct {
	Id       uint32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Siblings []uint32 `protobuf:"varint,2,rep,packed,name=siblings" json:"siblings,omitempty"`
}

func (m *CPU) Reset()                    { *m = CPU{} }
func (m *CPU) String() string            { return proto.CompactTextString(m) }
func (*CPU) ProtoMessage()               {}
func (*CPU) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CPU) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CPU) GetSiblings() []uint32 {
	if m != nil {
		return m.Siblings
	}
	return nil
}

type Sibling struct {
	Id    uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Value uint64 `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
}

func (m *Sibling) Reset()                    { *m = Sibling{} }
func (m *Sibling) String() string            { return proto.CompactTextString(m) }
func (*Sibling) ProtoMessage()               {}
func (*Sibling) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Sibling) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Sibling) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Pages struct {
	Count uint64 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
	Unit  string `protobuf:"bytes,2,opt,name=unit" json:"unit,omitempty"`
	Size  uint32 `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
}

func (m *Pages) Reset()                    { *m = Pages{} }
func (m *Pages) String() string            { return proto.CompactTextString(m) }
func (*Pages) ProtoMessage()               {}
func (*Pages) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Pages) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Pages) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *Pages) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Memory struct {
	Amount uint64 `protobuf:"varint,1,opt,name=amount" json:"amount,omitempty"`
	Unit   string `protobuf:"bytes,2,opt,name=unit" json:"unit,omitempty"`
}

func (m *Memory) Reset()                    { *m = Memory{} }
func (m *Memory) String() string            { return proto.CompactTextString(m) }
func (*Memory) ProtoMessage()               {}
func (*Memory) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Memory) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Memory) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

type Cell struct {
	Id        uint32     `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Memory    *Memory    `protobuf:"bytes,2,opt,name=memory" json:"memory,omitempty"`
	Pages     []*Pages   `protobuf:"bytes,3,rep,name=pages" json:"pages,omitempty"`
	Distances []*Sibling `protobuf:"bytes,4,rep,name=distances" json:"distances,omitempty"`
	Cpus      []*CPU     `protobuf:"bytes,5,rep,name=cpus" json:"cpus,omitempty"`
}

func (m *Cell) Reset()                    { *m = Cell{} }
func (m *Cell) String() string            { return proto.CompactTextString(m) }
func (*Cell) ProtoMessage()               {}
func (*Cell) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Cell) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Cell) GetMemory() *Memory {
	if m != nil {
		return m.Memory
	}
	return nil
}

func (m *Cell) GetPages() []*Pages {
	if m != nil {
		return m.Pages
	}
	return nil
}

func (m *Cell) GetDistances() []*Sibling {
	if m != nil {
		return m.Distances
	}
	return nil
}

func (m *Cell) GetCpus() []*CPU {
	if m != nil {
		return m.Cpus
	}
	return nil
}

type Topology struct {
	NumaCells []*Cell `protobuf:"bytes,1,rep,name=numa_cells,json=numaCells" json:"numa_cells,omitempty"`
}

func (m *Topology) Reset()                    { *m = Topology{} }
func (m *Topology) String() string            { return proto.CompactTextString(m) }
func (*Topology) ProtoMessage()               {}
func (*Topology) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Topology) GetNumaCells() []*Cell {
	if m != nil {
		return m.NumaCells
	}
	return nil
}

type SMBios struct {
	Manufacturer string `protobuf:"bytes,1,opt,name=manufacturer" json:"manufacturer,omitempty"`
	Product      string `protobuf:"bytes,2,opt,name=product" json:"product,omitempty"`
	Version      string `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	Sku          string `protobuf:"bytes,4,opt,name=sku" json:"sku,omitempty"`
	Family       string `protobuf:"bytes,5,opt,name=family" json:"family,omitempty"`
}

func (m *SMBios) Reset()                    { *m = SMBios{} }
func (m *SMBios) String() string            { return proto.CompactTextString(m) }
func (*SMBios) ProtoMessage()               {}
func (*SMBios) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *SMBios) GetManufacturer() string {
	if m != nil {
		return m.Manufacturer
	}
	return ""
}

func (m *SMBios) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func (m *SMBios) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *SMBios) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *SMBios) GetFamily() string {
	if m != nil {
		return m.Family
	}
	return ""
}

type DiskInfo struct {
	Format      string `protobuf:"bytes,1,opt,name=format" json:"format,omitempty"`
	BackingFile string `protobuf:"bytes,2,opt,name=backingFile" json:"backingFile,omitempty"`
	ActualSize  uint64 `protobuf:"varint,3,opt,name=actualSize" json:"actualSize,omitempty"`
	VirtualSize uint64 `protobuf:"varint,4,opt,name=virtualSize" json:"virtualSize,omitempty"`
}

func (m *DiskInfo) Reset()                    { *m = DiskInfo{} }
func (m *DiskInfo) String() string            { return proto.CompactTextString(m) }
func (*DiskInfo) ProtoMessage()               {}
func (*DiskInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *DiskInfo) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *DiskInfo) GetBackingFile() string {
	if m != nil {
		return m.BackingFile
	}
	return ""
}

func (m *DiskInfo) GetActualSize() uint64 {
	if m != nil {
		return m.ActualSize
	}
	return 0
}

func (m *DiskInfo) GetVirtualSize() uint64 {
	if m != nil {
		return m.VirtualSize
	}
	return 0
}

type ClusterConfig struct {
	ExpandDisksEnabled        bool `protobuf:"varint,1,opt,name=ExpandDisksEnabled" json:"ExpandDisksEnabled,omitempty"`
	FreePageReportingDisabled bool `protobuf:"varint,2,opt,name=FreePageReportingDisabled" json:"FreePageReportingDisabled,omitempty"`
	BochsDisplayForEFIGuests  bool `protobuf:"varint,3,opt,name=BochsDisplayForEFIGuests" json:"BochsDisplayForEFIGuests,omitempty"`
	SerialConsoleLogDisabled  bool `protobuf:"varint,4,opt,name=SerialConsoleLogDisabled" json:"SerialConsoleLogDisabled,omitempty"`
	DownwardMetricsEnabled    bool `protobuf:"varint,5,opt,name=DownwardMetricsEnabled" json:"DownwardMetricsEnabled,omitempty"`
}

func (m *ClusterConfig) Reset()                    { *m = ClusterConfig{} }
func (m *ClusterConfig) String() string            { return proto.CompactTextString(m) }
func (*ClusterConfig) ProtoMessage()               {}
func (*ClusterConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ClusterConfig) GetExpandDisksEnabled() bool {
	if m != nil {
		return m.ExpandDisksEnabled
	}
	return false
}

func (m *ClusterConfig) GetFreePageReportingDisabled() bool {
	if m != nil {
		return m.FreePageReportingDisabled
	}
	return false
}

func (m *ClusterConfig) GetBochsDisplayForEFIGuests() bool {
	if m != nil {
		return m.BochsDisplayForEFIGuests
	}
	return false
}

func (m *ClusterConfig) GetSerialConsoleLogDisabled() bool {
	if m != nil {
		return m.SerialConsoleLogDisabled
	}
	return false
}

func (m *ClusterConfig) GetDownwardMetricsEnabled() bool {
	if m != nil {
		return m.DownwardMetricsEnabled
	}
	return false
}

type InterfaceBindingMigration struct {
	Method string `protobuf:"bytes,1,opt,name=Method" json:"Method,omitempty"`
}

func (m *InterfaceBindingMigration) Reset()                    { *m = InterfaceBindingMigration{} }
func (m *InterfaceBindingMigration) String() string            { return proto.CompactTextString(m) }
func (*InterfaceBindingMigration) ProtoMessage()               {}
func (*InterfaceBindingMigration) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *InterfaceBindingMigration) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

type VirtualMachineOptions struct {
	VirtualMachineSMBios  *SMBios              `protobuf:"bytes,1,opt,name=VirtualMachineSMBios" json:"VirtualMachineSMBios,omitempty"`
	MemBalloonStatsPeriod uint32               `protobuf:"varint,2,opt,name=MemBalloonStatsPeriod" json:"MemBalloonStatsPeriod,omitempty"`
	PreallocatedVolumes   []string             `protobuf:"bytes,3,rep,name=PreallocatedVolumes" json:"PreallocatedVolumes,omitempty"`
	Topology              *Topology            `protobuf:"bytes,4,opt,name=topology" json:"topology,omitempty"`
	DisksInfo             map[string]*DiskInfo `protobuf:"bytes,5,rep,name=DisksInfo" json:"DisksInfo,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Deprecated, use clusterConfig.ExpandDisksEnabled
	ExpandDisksEnabled        bool                                  `protobuf:"varint,6,opt,name=ExpandDisksEnabled" json:"ExpandDisksEnabled,omitempty"`
	ClusterConfig             *ClusterConfig                        `protobuf:"bytes,7,opt,name=clusterConfig" json:"clusterConfig,omitempty"`
	InterfaceDomainAttachment map[string]string                     `protobuf:"bytes,8,rep,name=interfaceDomainAttachment" json:"interfaceDomainAttachment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	InterfaceMigration        map[string]*InterfaceBindingMigration `protobuf:"bytes,9,rep,name=interfaceMigration" json:"interfaceMigration,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *VirtualMachineOptions) Reset()                    { *m = VirtualMachineOptions{} }
func (m *VirtualMachineOptions) String() string            { return proto.CompactTextString(m) }
func (*VirtualMachineOptions) ProtoMessage()               {}
func (*VirtualMachineOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *VirtualMachineOptions) GetVirtualMachineSMBios() *SMBios {
	if m != nil {
		return m.VirtualMachineSMBios
	}
	return nil
}

func (m *VirtualMachineOptions) GetMemBalloonStatsPeriod() uint32 {
	if m != nil {
		return m.MemBalloonStatsPeriod
	}
	return 0
}

func (m *VirtualMachineOptions) GetPreallocatedVolumes() []string {
	if m != nil {
		return m.PreallocatedVolumes
	}
	return nil
}

func (m *VirtualMachineOptions) GetTopology() *Topology {
	if m != nil {
		return m.Topology
	}
	return nil
}

func (m *VirtualMachineOptions) GetDisksInfo() map[string]*DiskInfo {
	if m != nil {
		return m.DisksInfo
	}
	return nil
}

func (m *VirtualMachineOptions) GetExpandDisksEnabled() bool {
	if m != nil {
		return m.ExpandDisksEnabled
	}
	return false
}

func (m *VirtualMachineOptions) GetClusterConfig() *ClusterConfig {
	if m != nil {
		return m.ClusterConfig
	}
	return nil
}

func (m *VirtualMachineOptions) GetInterfaceDomainAttachment() map[string]string {
	if m != nil {
		return m.InterfaceDomainAttachment
	}
	return nil
}

func (m *VirtualMachineOptions) GetInterfaceMigration() map[string]*InterfaceBindingMigration {
	if m != nil {
		return m.InterfaceMigration
	}
	return nil
}

type VMIRequest struct {
	Vmi     *VMI                   `protobuf:"bytes,1,opt,name=vmi" json:"vmi,omitempty"`
	Options *VirtualMachineOptions `protobuf:"bytes,2,opt,name=options" json:"options,omitempty"`
}

func (m *VMIRequest) Reset()                    { *m = VMIRequest{} }
func (m *VMIRequest) String() string            { return proto.CompactTextString(m) }
func (*VMIRequest) ProtoMessage()               {}
func (*VMIRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *VMIRequest) GetVmi() *VMI {
	if m != nil {
		return m.Vmi
	}
	return nil
}

func (m *VMIRequest) GetOptions() *VirtualMachineOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type MigrationRequest struct {
	Vmi     *VMI   `protobuf:"bytes,1,opt,name=vmi" json:"vmi,omitempty"`
	Options []byte `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
}

func (m *MigrationRequest) Reset()                    { *m = MigrationRequest{} }
func (m *MigrationRequest) String() string            { return proto.CompactTextString(m) }
func (*MigrationRequest) ProtoMessage()               {}
func (*MigrationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *MigrationRequest) GetVmi() *VMI {
	if m != nil {
		return m.Vmi
	}
	return nil
}

func (m *MigrationRequest) GetOptions() []byte {
	if m != nil {
		return m.Options
	}
	return nil
}

type ExecRequest struct {
	DomainName     string   `protobuf:"bytes,1,opt,name=domainName" json:"domainName,omitempty"`
	Command        string   `protobuf:"bytes,2,opt,name=Command" json:"Command,omitempty"`
	Args           []string `protobuf:"bytes,3,rep,name=Args" json:"Args,omitempty"`
	TimeoutSeconds int32    `protobuf:"varint,4,opt,name=timeoutSeconds" json:"timeoutSeconds,omitempty"`
}

func (m *ExecRequest) Reset()                    { *m = ExecRequest{} }
func (m *ExecRequest) String() string            { return proto.CompactTextString(m) }
func (*ExecRequest) ProtoMessage()               {}
func (*ExecRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *ExecRequest) GetDomainName() string {
	if m != nil {
		return m.DomainName
	}
	return ""
}

func (m *ExecRequest) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *ExecRequest) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *ExecRequest) GetTimeoutSeconds() int32 {
	if m != nil {
		return m.TimeoutSeconds
	}
	return 0
}

type EmptyRequest struct {
}

func (m *EmptyRequest) Reset()                    { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string            { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()               {}
func (*EmptyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type Response struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DomainResponse struct {
	Response *Response `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
	Domain   string    `protobuf:"bytes,2,opt,name=domain" json:"domain,omitempty"`
}

func (m *DomainResponse) Reset()                    { *m = DomainResponse{} }
func (m *DomainResponse) String() string            { return proto.CompactTextString(m) }
func (*DomainResponse) ProtoMessage()               {}
func (*DomainResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *DomainResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *DomainResponse) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

type DomainStatsResponse struct {
	Response    *Response `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
	DomainStats string    `protobuf:"bytes,2,opt,name=domainStats" json:"domainStats,omitempty"`
}

func (m *DomainStatsResponse) Reset()                    { *m = DomainStatsResponse{} }
func (m *DomainStatsResponse) String() string            { return proto.CompactTextString(m) }
func (*DomainStatsResponse) ProtoMessage()               {}
func (*DomainStatsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *DomainStatsResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *DomainStatsResponse) GetDomainStats() string {
	if m != nil {
		return m.DomainStats
	}
	return ""
}

type GuestInfoResponse struct {
	Response          *Response `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
	GuestInfoResponse string    `protobuf:"bytes,2,opt,name=guestInfoResponse" json:"guestInfoResponse,omitempty"`
}

func (m *GuestInfoResponse) Reset()                    { *m = GuestInfoResponse{} }
func (m *GuestInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*GuestInfoResponse) ProtoMessage()               {}
func (*GuestInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *GuestInfoResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GuestInfoResponse) GetGuestInfoResponse() string {
	if m != nil {
		return m.GuestInfoResponse
	}
	return ""
}

type GuestUserListResponse struct {
	Response              *Response `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
	GuestUserListResponse string    `protobuf:"bytes,2,opt,name=guestUserListResponse" json:"guestUserListResponse,omitempty"`
}

func (m *GuestUserListResponse) Reset()                    { *m = GuestUserListResponse{} }
func (m *GuestUserListResponse) String() string            { return proto.CompactTextString(m) }
func (*GuestUserListResponse) ProtoMessage()               {}
func (*GuestUserListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *GuestUserListResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GuestUserListResponse) GetGuestUserListResponse() string {
	if m != nil {
		return m.GuestUserListResponse
	}
	return ""
}

type GuestFilesystemsResponse struct {
	Response                 *Response `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
	GuestFilesystemsResponse string    `protobuf:"bytes,2,opt,name=guestFilesystemsResponse" json:"guestFilesystemsResponse,omitempty"`
}

func (m *GuestFilesystemsResponse) Reset()                    { *m = GuestFilesystemsResponse{} }
func (m *GuestFilesystemsResponse) String() string            { return proto.CompactTextString(m) }
func (*GuestFilesystemsResponse) ProtoMessage()               {}
func (*GuestFilesystemsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *GuestFilesystemsResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GuestFilesystemsResponse) GetGuestFilesystemsResponse() string {
	if m != nil {
		return m.GuestFilesystemsResponse
	}
	return ""
}

type ExecResponse struct {
	Response *Response `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
	ExitCode int32     `protobuf:"varint,2,opt,name=exitCode" json:"exitCode,omitempty"`
	StdOut   string    `protobuf:"bytes,3,opt,name=stdOut" json:"stdOut,omitempty"`
}

func (m *ExecResponse) Reset()                    { *m = ExecResponse{} }
func (m *ExecResponse) String() string            { return proto.CompactTextString(m) }
func (*ExecResponse) ProtoMessage()               {}
func (*ExecResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *ExecResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *ExecResponse) GetExitCode() int32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *ExecResponse) GetStdOut() string {
	if m != nil {
		return m.StdOut
	}
	return ""
}

type GuestPingRequest struct {
	DomainName     string `protobuf:"bytes,1,opt,name=domainName" json:"domainName,omitempty"`
	TimeoutSeconds int32  `protobuf:"varint,2,opt,name=timeoutSeconds" json:"timeoutSeconds,omitempty"`
}

func (m *GuestPingRequest) Reset()                    { *m = GuestPingRequest{} }
func (m *GuestPingRequest) String() string            { return proto.CompactTextString(m) }
func (*GuestPingRequest) ProtoMessage()               {}
func (*GuestPingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *GuestPingRequest) GetDomainName() string {
	if m != nil {
		return m.DomainName
	}
	return ""
}

func (m *GuestPingRequest) GetTimeoutSeconds() int32 {
	if m != nil {
		return m.TimeoutSeconds
	}
	return 0
}

type GuestPingResponse struct {
	Response *Response `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
}

func (m *GuestPingResponse) Reset()                    { *m = GuestPingResponse{} }
func (m *GuestPingResponse) String() string            { return proto.CompactTextString(m) }
func (*GuestPingResponse) ProtoMessage()               {}
func (*GuestPingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *GuestPingResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

type FreezeRequest struct {
	Vmi                    *VMI  `protobuf:"bytes,1,opt,name=vmi" json:"vmi,omitempty"`
	UnfreezeTimeoutSeconds int32 `protobuf:"varint,2,opt,name=unfreezeTimeoutSeconds" json:"unfreezeTimeoutSeconds,omitempty"`
}

func (m *FreezeRequest) Reset()                    { *m = FreezeRequest{} }
func (m *FreezeRequest) String() string            { return proto.CompactTextString(m) }
func (*FreezeRequest) ProtoMessage()               {}
func (*FreezeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *FreezeRequest) GetVmi() *VMI {
	if m != nil {
		return m.Vmi
	}
	return nil
}

func (m *FreezeRequest) GetUnfreezeTimeoutSeconds() int32 {
	if m != nil {
		return m.UnfreezeTimeoutSeconds
	}
	return 0
}

type MemoryDumpRequest struct {
	Vmi      *VMI   `protobuf:"bytes,1,opt,name=vmi" json:"vmi,omitempty"`
	DumpPath string `protobuf:"bytes,2,opt,name=dumpPath" json:"dumpPath,omitempty"`
}

func (m *MemoryDumpRequest) Reset()                    { *m = MemoryDumpRequest{} }
func (m *MemoryDumpRequest) String() string            { return proto.CompactTextString(m) }
func (*MemoryDumpRequest) ProtoMessage()               {}
func (*MemoryDumpRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *MemoryDumpRequest) GetVmi() *VMI {
	if m != nil {
		return m.Vmi
	}
	return nil
}

func (m *MemoryDumpRequest) GetDumpPath() string {
	if m != nil {
		return m.DumpPath
	}
	return ""
}

type SEVInfoResponse struct {
	Response *Response `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
	SevInfo  []byte    `protobuf:"bytes,2,opt,name=sevInfo,proto3" json:"sevInfo,omitempty"`
}

func (m *SEVInfoResponse) Reset()                    { *m = SEVInfoResponse{} }
func (m *SEVInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*SEVInfoResponse) ProtoMessage()               {}
func (*SEVInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *SEVInfoResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *SEVInfoResponse) GetSevInfo() []byte {
	if m != nil {
		return m.SevInfo
	}
	return nil
}

type LaunchMeasurementResponse struct {
	Response          *Response `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
	LaunchMeasurement []byte    `protobuf:"bytes,2,opt,name=launchMeasurement,proto3" json:"launchMeasurement,omitempty"`
}

func (m *LaunchMeasurementResponse) Reset()                    { *m = LaunchMeasurementResponse{} }
func (m *LaunchMeasurementResponse) String() string            { return proto.CompactTextString(m) }
func (*LaunchMeasurementResponse) ProtoMessage()               {}
func (*LaunchMeasurementResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *LaunchMeasurementResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *LaunchMeasurementResponse) GetLaunchMeasurement() []byte {
	if m != nil {
		return m.LaunchMeasurement
	}
	return nil
}

type InjectLaunchSecretRequest struct {
	Vmi     *VMI   `protobuf:"bytes,1,opt,name=vmi" json:"vmi,omitempty"`
	Options []byte `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
}

func (m *InjectLaunchSecretRequest) Reset()                    { *m = InjectLaunchSecretRequest{} }
func (m *InjectLaunchSecretRequest) String() string            { return proto.CompactTextString(m) }
func (*InjectLaunchSecretRequest) ProtoMessage()               {}
func (*InjectLaunchSecretRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *InjectLaunchSecretRequest) GetVmi() *VMI {
	if m != nil {
		return m.Vmi
	}
	return nil
}

func (m *InjectLaunchSecretRequest) GetOptions() []byte {
	if m != nil {
		return m.Options
	}
	return nil
}

func init() {
	proto.RegisterType((*QemuVersionResponse)(nil), "kubevirt.cmd.v1.QemuVersionResponse")
	proto.RegisterType((*VMI)(nil), "kubevirt.cmd.v1.VMI")
	proto.RegisterType((*CPU)(nil), "kubevirt.cmd.v1.CPU")
	proto.RegisterType((*Sibling)(nil), "kubevirt.cmd.v1.Sibling")
	proto.RegisterType((*Pages)(nil), "kubevirt.cmd.v1.Pages")
	proto.RegisterType((*Memory)(nil), "kubevirt.cmd.v1.Memory")
	proto.RegisterType((*Cell)(nil), "kubevirt.cmd.v1.Cell")
	proto.RegisterType((*Topology)(nil), "kubevirt.cmd.v1.Topology")
	proto.RegisterType((*SMBios)(nil), "kubevirt.cmd.v1.SMBios")
	proto.RegisterType((*DiskInfo)(nil), "kubevirt.cmd.v1.DiskInfo")
	proto.RegisterType((*ClusterConfig)(nil), "kubevirt.cmd.v1.ClusterConfig")
	proto.RegisterType((*InterfaceBindingMigration)(nil), "kubevirt.cmd.v1.InterfaceBindingMigration")
	proto.RegisterType((*VirtualMachineOptions)(nil), "kubevirt.cmd.v1.VirtualMachineOptions")
	proto.RegisterType((*VMIRequest)(nil), "kubevirt.cmd.v1.VMIRequest")
	proto.RegisterType((*MigrationRequest)(nil), "kubevirt.cmd.v1.MigrationRequest")
	proto.RegisterType((*ExecRequest)(nil), "kubevirt.cmd.v1.ExecRequest")
	proto.RegisterType((*EmptyRequest)(nil), "kubevirt.cmd.v1.EmptyRequest")
	proto.RegisterType((*Response)(nil), "kubevirt.cmd.v1.Response")
	proto.RegisterType((*DomainResponse)(nil), "kubevirt.cmd.v1.DomainResponse")
	proto.RegisterType((*DomainStatsResponse)(nil), "kubevirt.cmd.v1.DomainStatsResponse")
	proto.RegisterType((*GuestInfoResponse)(nil), "kubevirt.cmd.v1.GuestInfoResponse")
	proto.RegisterType((*GuestUserListResponse)(nil), "kubevirt.cmd.v1.GuestUserListResponse")
	proto.RegisterType((*GuestFilesystemsResponse)(nil), "kubevirt.cmd.v1.GuestFilesystemsResponse")
	proto.RegisterType((*ExecResponse)(nil), "kubevirt.cmd.v1.ExecResponse")
	proto.RegisterType((*GuestPingRequest)(nil), "kubevirt.cmd.v1.GuestPingRequest")
	proto.RegisterType((*GuestPingResponse)(nil), "kubevirt.cmd.v1.GuestPingResponse")
	proto.RegisterType((*FreezeRequest)(nil), "kubevirt.cmd.v1.FreezeRequest")
	proto.RegisterType((*MemoryDumpRequest)(nil), "kubevirt.cmd.v1.MemoryDumpRequest")
	proto.RegisterType((*SEVInfoResponse)(nil), "kubevirt.cmd.v1.SEVInfoResponse")
	proto.RegisterType((*LaunchMeasurementResponse)(nil), "kubevirt.cmd.v1.LaunchMeasurementResponse")
	proto.RegisterType((*InjectLaunchSecretRequest)(nil), "kubevirt.cmd.v1.InjectLaunchSecretRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Cmd service

type CmdClient interface {
	SyncVirtualMachine(ctx context.Context, in *VMIRequest, opts ...grpc.CallOption) (*Response, error)
	PauseVirtualMachine(ctx context.Context, in *VMIRequest, opts ...grpc.CallOption) (*Response, error)
	UnpauseVirtualMachine(ctx context.Context, in *VMIRequest, opts ...grpc.CallOption) (*Response, error)
	FreezeVirtualMachine(ctx context.Context, in *FreezeRequest, opts ...grpc.CallOption) (*Response, error)
	UnfreezeVirtualMachine(ctx context.Context, in *VMIRequest, opts ...grpc.CallOption) (*Response, error)
	SoftRebootVirtualMachine(ctx context.Context, in *VMIRequest, opts ...grpc.CallOption) (*Response, error)
	ShutdownVirtualMachine(ctx context.Context, in *VMIRequest, opts ...grpc.CallOption) (*Response, error)
	KillVirtualMachine(ctx context.Context, in *VMIRequest, opts ...grpc.CallOption) (*Response, error)
	DeleteVirtualMachine(ctx context.Context, in *VMIRequest, opts ...grpc.CallOption) (*Response, error)
	MigrateVirtualMachine(ctx context.Context, in *MigrationRequest, opts ...grpc.CallOption) (*Response, error)
	SyncMigrationTarget(ctx context.Context, in *VMIRequest, opts ...grpc.CallOption) (*Response, error)
	CancelVirtualMachineMigration(ctx context.Context, in *VMIRequest, opts ...grpc.CallOption) (*Response, error)
	SignalTargetPodCleanup(ctx context.Context, in *VMIRequest, opts ...grpc.CallOption) (*Response, error)
	FinalizeVirtualMachineMigration(ctx context.Context, in *VMIRequest, opts ...grpc.CallOption) (*Response, error)
	HotplugHostDevices(ctx context.Context, in *VMIRequest, opts ...grpc.CallOption) (*Response, error)
	GetDomain(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*DomainResponse, error)
	GetDomainStats(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*DomainStatsResponse, error)
	GetGuestInfo(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GuestInfoResponse, error)
	GetUsers(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GuestUserListResponse, error)
	GetFilesystems(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GuestFilesystemsResponse, error)
	Ping(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*Response, error)
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error)
	GuestPing(ctx context.Context, in *GuestPingRequest, opts ...grpc.CallOption) (*GuestPingResponse, error)
	VirtualMachineMemoryDump(ctx context.Context, in *MemoryDumpRequest, opts ...grpc.CallOption) (*Response, error)
	GetQemuVersion(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*QemuVersionResponse, error)
	SyncVirtualMachineCPUs(ctx context.Context, in *VMIRequest, opts ...grpc.CallOption) (*Response, error)
	SyncVirtualMachineMemory(ctx context.Context, in *VMIRequest, opts ...grpc.CallOption) (*Response, error)
	GetSEVInfo(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*SEVInfoResponse, error)
	GetLaunchMeasurement(ctx context.Context, in *VMIRequest, opts ...grpc.CallOption) (*LaunchMeasurementResponse, error)
	InjectLaunchSecret(ctx context.Context, in *InjectLaunchSecretRequest, opts ...grpc.CallOption) (*Response, error)
}

type cmdClient struct {
	cc *grpc.ClientConn
}

func NewCmdClient(cc *grpc.ClientConn) CmdClient {
	return &cmdClient{cc}
}

func (c *cmdClient) SyncVirtualMachine(ctx context.Context, in *VMIRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/kubevirt.cmd.v1.Cmd/SyncVirtualMachine", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdClient) PauseVirtualMachine(ctx context.Context, in *VMIRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/kubevirt.cmd.v1.Cmd/PauseVirtualMachine", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdClient) UnpauseVirtualMachine(ctx context.Context, in *VMIRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/kubevirt.cmd.v1.Cmd/UnpauseVirtualMachine", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdClient) FreezeVirtualMachine(ctx context.Context, in *FreezeRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/kubevirt.cmd.v1.Cmd/FreezeVirtualMachine", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdClient) UnfreezeVirtualMachine(ctx context.Context, in *VMIRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/kubevirt.cmd.v1.Cmd/UnfreezeVirtualMachine", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdClient) SoftRebootVirtualMachine(ctx context.Context, in *VMIRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/kubevirt.cmd.v1.Cmd/SoftRebootVirtualMachine", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdClient) ShutdownVirtualMachine(ctx context.Context, in *VMIRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/kubevirt.cmd.v1.Cmd/ShutdownVirtualMachine", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdClient) KillVirtualMachine(ctx context.Context, in *VMIRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/kubevirt.cmd.v1.Cmd/KillVirtualMachine", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdClient) DeleteVirtualMachine(ctx context.Context, in *VMIRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/kubevirt.cmd.v1.Cmd/DeleteVirtualMachine", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdClient) MigrateVirtualMachine(ctx context.Context, in *MigrationRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/kubevirt.cmd.v1.Cmd/MigrateVirtualMachine", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdClient) SyncMigrationTarget(ctx context.Context, in *VMIRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/kubevirt.cmd.v1.Cmd/SyncMigrationTarget", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdClient) CancelVirtualMachineMigration(ctx context.Context, in *VMIRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/kubevirt.cmd.v1.Cmd/CancelVirtualMachineMigration", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdClient) SignalTargetPodCleanup(ctx context.Context, in *VMIRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/kubevirt.cmd.v1.Cmd/SignalTargetPodCleanup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdClient) FinalizeVirtualMachineMigration(ctx context.Context, in *VMIRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/kubevirt.cmd.v1.Cmd/FinalizeVirtualMachineMigration", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdClient) HotplugHostDevices(ctx context.Context, in *VMIRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/kubevirt.cmd.v1.Cmd/HotplugHostDevices", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdClient) GetDomain(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*DomainResponse, error) {
	out := new(DomainResponse)
	err := grpc.Invoke(ctx, "/kubevirt.cmd.v1.Cmd/GetDomain", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdClient) GetDomainStats(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*DomainStatsResponse, error) {
	out := new(DomainStatsResponse)
	err := grpc.Invoke(ctx, "/kubevirt.cmd.v1.Cmd/GetDomainStats", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdClient) GetGuestInfo(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GuestInfoResponse, error) {
	out := new(GuestInfoResponse)
	err := grpc.Invoke(ctx, "/kubevirt.cmd.v1.Cmd/GetGuestInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdClient) GetUsers(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GuestUserListResponse, error) {
	out := new(GuestUserListResponse)
	err := grpc.Invoke(ctx, "/kubevirt.cmd.v1.Cmd/GetUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdClient) GetFilesystems(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GuestFilesystemsResponse, error) {
	out := new(GuestFilesystemsResponse)
	err := grpc.Invoke(ctx, "/kubevirt.cmd.v1.Cmd/GetFilesystems", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdClient) Ping(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/kubevirt.cmd.v1.Cmd/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	out := new(ExecResponse)
	err := grpc.Invoke(ctx, "/kubevirt.cmd.v1.Cmd/Exec", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdClient) GuestPing(ctx context.Context, in *GuestPingRequest, opts ...grpc.CallOption) (*GuestPingResponse, error) {
	out := new(GuestPingResponse)
	err := grpc.Invoke(ctx, "/kubevirt.cmd.v1.Cmd/GuestPing", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdClient) VirtualMachineMemoryDump(ctx context.Context, in *MemoryDumpRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/kubevirt.cmd.v1.Cmd/VirtualMachineMemoryDump", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdClient) GetQemuVersion(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*QemuVersionResponse, error) {
	out := new(QemuVersionResponse)
	err := grpc.Invoke(ctx, "/kubevirt.cmd.v1.Cmd/GetQemuVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdClient) SyncVirtualMachineCPUs(ctx context.Context, in *VMIRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/kubevirt.cmd.v1.Cmd/SyncVirtualMachineCPUs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdClient) SyncVirtualMachineMemory(ctx context.Context, in *VMIRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/kubevirt.cmd.v1.Cmd/SyncVirtualMachineMemory", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdClient) GetSEVInfo(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*SEVInfoResponse, error) {
	out := new(SEVInfoResponse)
	err := grpc.Invoke(ctx, "/kubevirt.cmd.v1.Cmd/GetSEVInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdClient) GetLaunchMeasurement(ctx context.Context, in *VMIRequest, opts ...grpc.CallOption) (*LaunchMeasurementResponse, error) {
	out := new(LaunchMeasurementResponse)
	err := grpc.Invoke(ctx, "/kubevirt.cmd.v1.Cmd/GetLaunchMeasurement", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdClient) InjectLaunchSecret(ctx context.Context, in *InjectLaunchSecretRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/kubevirt.cmd.v1.Cmd/InjectLaunchSecret", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Cmd service

type CmdServer interface {
	SyncVirtualMachine(context.Context, *VMIRequest) (*Response, error)
	PauseVirtualMachine(context.Context, *VMIRequest) (*Response, error)
	UnpauseVirtualMachine(context.Context, *VMIRequest) (*Response, error)
	FreezeVirtualMachine(context.Context, *FreezeRequest) (*Response, error)
	UnfreezeVirtualMachine(context.Context, *VMIRequest) (*Response, error)
	SoftRebootVirtualMachine(context.Context, *VMIRequest) (*Response, error)
	ShutdownVirtualMachine(context.Context, *VMIRequest) (*Response, error)
	KillVirtualMachine(context.Context, *VMIRequest) (*Response, error)
	DeleteVirtualMachine(context.Context, *VMIRequest) (*Response, error)
	MigrateVirtualMachine(context.Context, *MigrationRequest) (*Response, error)
	SyncMigrationTarget(context.Context, *VMIRequest) (*Response, error)
	CancelVirtualMachineMigration(context.Context, *VMIRequest) (*Response, error)
	SignalTargetPodCleanup(context.Context, *VMIRequest) (*Response, error)
	FinalizeVirtualMachineMigration(context.Context, *VMIRequest) (*Response, error)
	HotplugHostDevices(context.Context, *VMIRequest) (*Response, error)
	GetDomain(context.Context, *EmptyRequest) (*DomainResponse, error)
	GetDomainStats(context.Context, *EmptyRequest) (*DomainStatsResponse, error)
	GetGuestInfo(context.Context, *EmptyRequest) (*GuestInfoResponse, error)
	GetUsers(context.Context, *EmptyRequest) (*GuestUserListResponse, error)
	GetFilesystems(context.Context, *EmptyRequest) (*GuestFilesystemsResponse, error)
	Ping(context.Context, *EmptyRequest) (*Response, error)
	Exec(context.Context, *ExecRequest) (*ExecResponse, error)
	GuestPing(context.Context, *GuestPingRequest) (*GuestPingResponse, error)
	VirtualMachineMemoryDump(context.Context, *MemoryDumpRequest) (*Response, error)
	GetQemuVersion(context.Context, *EmptyRequest) (*QemuVersionResponse, error)
	SyncVirtualMachineCPUs(context.Context, *VMIRequest) (*Response, error)
	SyncVirtualMachineMemory(context.Context, *VMIRequest) (*Response, error)
	GetSEVInfo(context.Context, *EmptyRequest) (*SEVInfoResponse, error)
	GetLaunchMeasurement(context.Context, *VMIRequest) (*LaunchMeasurementResponse, error)
	InjectLaunchSecret(context.Context, *InjectLaunchSecretRequest) (*Response, error)
}

func RegisterCmdServer(s *grpc.Server, srv CmdServer) {
	s.RegisterService(&_Cmd_serviceDesc, srv)
}

func _Cmd_SyncVirtualMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdServer).SyncVirtualMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.cmd.v1.Cmd/SyncVirtualMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdServer).SyncVirtualMachine(ctx, req.(*VMIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cmd_PauseVirtualMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdServer).PauseVirtualMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.cmd.v1.Cmd/PauseVirtualMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdServer).PauseVirtualMachine(ctx, req.(*VMIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cmd_UnpauseVirtualMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdServer).UnpauseVirtualMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.cmd.v1.Cmd/UnpauseVirtualMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdServer).UnpauseVirtualMachine(ctx, req.(*VMIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cmd_FreezeVirtualMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FreezeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdServer).FreezeVirtualMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.cmd.v1.Cmd/FreezeVirtualMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdServer).FreezeVirtualMachine(ctx, req.(*FreezeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cmd_UnfreezeVirtualMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdServer).UnfreezeVirtualMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.cmd.v1.Cmd/UnfreezeVirtualMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdServer).UnfreezeVirtualMachine(ctx, req.(*VMIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cmd_SoftRebootVirtualMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdServer).SoftRebootVirtualMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.cmd.v1.Cmd/SoftRebootVirtualMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdServer).SoftRebootVirtualMachine(ctx, req.(*VMIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cmd_ShutdownVirtualMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdServer).ShutdownVirtualMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.cmd.v1.Cmd/ShutdownVirtualMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdServer).ShutdownVirtualMachine(ctx, req.(*VMIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cmd_KillVirtualMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdServer).KillVirtualMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.cmd.v1.Cmd/KillVirtualMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdServer).KillVirtualMachine(ctx, req.(*VMIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cmd_DeleteVirtualMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdServer).DeleteVirtualMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.cmd.v1.Cmd/DeleteVirtualMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdServer).DeleteVirtualMachine(ctx, req.(*VMIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cmd_MigrateVirtualMachine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdServer).MigrateVirtualMachine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.cmd.v1.Cmd/MigrateVirtualMachine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdServer).MigrateVirtualMachine(ctx, req.(*MigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cmd_SyncMigrationTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdServer).SyncMigrationTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.cmd.v1.Cmd/SyncMigrationTarget",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdServer).SyncMigrationTarget(ctx, req.(*VMIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cmd_CancelVirtualMachineMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdServer).CancelVirtualMachineMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.cmd.v1.Cmd/CancelVirtualMachineMigration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdServer).CancelVirtualMachineMigration(ctx, req.(*VMIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cmd_SignalTargetPodCleanup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdServer).SignalTargetPodCleanup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.cmd.v1.Cmd/SignalTargetPodCleanup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdServer).SignalTargetPodCleanup(ctx, req.(*VMIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cmd_FinalizeVirtualMachineMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdServer).FinalizeVirtualMachineMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.cmd.v1.Cmd/FinalizeVirtualMachineMigration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdServer).FinalizeVirtualMachineMigration(ctx, req.(*VMIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cmd_HotplugHostDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdServer).HotplugHostDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.cmd.v1.Cmd/HotplugHostDevices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdServer).HotplugHostDevices(ctx, req.(*VMIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cmd_GetDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdServer).GetDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.cmd.v1.Cmd/GetDomain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdServer).GetDomain(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cmd_GetDomainStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdServer).GetDomainStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.cmd.v1.Cmd/GetDomainStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdServer).GetDomainStats(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cmd_GetGuestInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdServer).GetGuestInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.cmd.v1.Cmd/GetGuestInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdServer).GetGuestInfo(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cmd_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.cmd.v1.Cmd/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdServer).GetUsers(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cmd_GetFilesystems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdServer).GetFilesystems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.cmd.v1.Cmd/GetFilesystems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdServer).GetFilesystems(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cmd_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.cmd.v1.Cmd/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdServer).Ping(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cmd_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.cmd.v1.Cmd/Exec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdServer).Exec(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cmd_GuestPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuestPingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdServer).GuestPing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.cmd.v1.Cmd/GuestPing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdServer).GuestPing(ctx, req.(*GuestPingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cmd_VirtualMachineMemoryDump_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemoryDumpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdServer).VirtualMachineMemoryDump(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.cmd.v1.Cmd/VirtualMachineMemoryDump",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdServer).VirtualMachineMemoryDump(ctx, req.(*MemoryDumpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cmd_GetQemuVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdServer).GetQemuVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.cmd.v1.Cmd/GetQemuVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdServer).GetQemuVersion(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cmd_SyncVirtualMachineCPUs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdServer).SyncVirtualMachineCPUs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.cmd.v1.Cmd/SyncVirtualMachineCPUs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdServer).SyncVirtualMachineCPUs(ctx, req.(*VMIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cmd_SyncVirtualMachineMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdServer).SyncVirtualMachineMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.cmd.v1.Cmd/SyncVirtualMachineMemory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdServer).SyncVirtualMachineMemory(ctx, req.(*VMIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cmd_GetSEVInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdServer).GetSEVInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.cmd.v1.Cmd/GetSEVInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdServer).GetSEVInfo(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cmd_GetLaunchMeasurement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdServer).GetLaunchMeasurement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.cmd.v1.Cmd/GetLaunchMeasurement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdServer).GetLaunchMeasurement(ctx, req.(*VMIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cmd_InjectLaunchSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InjectLaunchSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdServer).InjectLaunchSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubevirt.cmd.v1.Cmd/InjectLaunchSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdServer).InjectLaunchSecret(ctx, req.(*InjectLaunchSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cmd_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kubevirt.cmd.v1.Cmd",
	HandlerType: (*CmdServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncVirtualMachine",
			Handler:    _Cmd_SyncVirtualMachine_Handler,
		},
		{
			MethodName: "PauseVirtualMachine",
			Handler:    _Cmd_PauseVirtualMachine_Handler,
		},
		{
			MethodName: "UnpauseVirtualMachine",
			Handler:    _Cmd_UnpauseVirtualMachine_Handler,
		},
		{
			MethodName: "FreezeVirtualMachine",
			Handler:    _Cmd_FreezeVirtualMachine_Handler,
		},
		{
			MethodName: "UnfreezeVirtualMachine",
			Handler:    _Cmd_UnfreezeVirtualMachine_Handler,
		},
		{
			MethodName: "SoftRebootVirtualMachine",
			Handler:    _Cmd_SoftRebootVirtualMachine_Handler,
		},
		{
			MethodName: "ShutdownVirtualMachine",
			Handler:    _Cmd_ShutdownVirtualMachine_Handler,
		},
		{
			MethodName: "KillVirtualMachine",
			Handler:    _Cmd_KillVirtualMachine_Handler,
		},
		{
			MethodName: "DeleteVirtualMachine",
			Handler:    _Cmd_DeleteVirtualMachine_Handler,
		},
		{
			MethodName: "MigrateVirtualMachine",
			Handler:    _Cmd_MigrateVirtualMachine_Handler,
		},
		{
			MethodName: "SyncMigrationTarget",
			Handler:    _Cmd_SyncMigrationTarget_Handler,
		},
		{
			MethodName: "CancelVirtualMachineMigration",
			Handler:    _Cmd_CancelVirtualMachineMigration_Handler,
		},
		{
			MethodName: "SignalTargetPodCleanup",
			Handler:    _Cmd_SignalTargetPodCleanup_Handler,
		},
		{
			MethodName: "FinalizeVirtualMachineMigration",
			Handler:    _Cmd_FinalizeVirtualMachineMigration_Handler,
		},
		{
			MethodName: "HotplugHostDevices",
			Handler:    _Cmd_HotplugHostDevices_Handler,
		},
		{
			MethodName: "GetDomain",
			Handler:    _Cmd_GetDomain_Handler,
		},
		{
			MethodName: "GetDomainStats",
			Handler:    _Cmd_GetDomainStats_Handler,
		},
		{
			MethodName: "GetGuestInfo",
			Handler:    _Cmd_GetGuestInfo_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _Cmd_GetUsers_Handler,
		},
		{
			MethodName: "GetFilesystems",
			Handler:    _Cmd_GetFilesystems_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Cmd_Ping_Handler,
		},
		{
			MethodName: "Exec",
			Handler:    _Cmd_Exec_Handler,
		},
		{
			MethodName: "GuestPing",
			Handler:    _Cmd_GuestPing_Handler,
		},
		{
			MethodName: "VirtualMachineMemoryDump",
			Handler:    _Cmd_VirtualMachineMemoryDump_Handler,
		},
		{
			MethodName: "GetQemuVersion",
			Handler:    _Cmd_GetQemuVersion_Handler,
		},
		{
			MethodName: "SyncVirtualMachineCPUs",
			Handler:    _Cmd_SyncVirtualMachineCPUs_Handler,
		},
		{
			MethodName: "SyncVirtualMachineMemory",
			Handler:    _Cmd_SyncVirtualMachineMemory_Handler,
		},
		{
			MethodName: "GetSEVInfo",
			Handler:    _Cmd_GetSEVInfo_Handler,
		},
		{
			MethodName: "GetLaunchMeasurement",
			Handler:    _Cmd_GetLaunchMeasurement_Handler,
		},
		{
			MethodName: "InjectLaunchSecret",
			Handler:    _Cmd_InjectLaunchSecret_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/handler-launcher-com/cmd/v1/cmd.proto",
}

func init() { proto.RegisterFile("pkg/handler-launcher-com/cmd/v1/cmd.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1824 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x59, 0x5f, 0x6f, 0x1b, 0xc7,
	0x11, 0x17, 0xff, 0x48, 0x22, 0x47, 0x7f, 0x62, 0xaf, 0xfe, 0xe4, 0xa4, 0xd6, 0xb6, 0x7a, 0x28,
	0x0c, 0xa5, 0x48, 0xa4, 0xda, 0x71, 0x8c, 0xc2, 0x28, 0x02, 0x47, 0x24, 0xa5, 0x28, 0x31, 0x6d,
	0xe6, 0x28, 0xc9, 0x68, 0xda, 0x20, 0x58, 0xdd, 0xad, 0xa8, 0xad, 0xee, 0x76, 0x99, 0xdb, 0x3d,
	0xda, 0xcc, 0x53, 0x81, 0x14, 0x7d, 0x28, 0xd0, 0x8f, 0xd2, 0xcf, 0xd3, 0xb7, 0x7e, 0x8e, 0x3e,
	0x16, 0xbb, 0xb7, 0x47, 0x1d, 0x79, 0x77, 0x92, 0x05, 0xf2, 0x89, 0xb7, 0x3b, 0x33, 0xbf, 0x99,
	0xdd, 0x9d, 0x99, 0xfd, 0xdd, 0x11, 0x3e, 0xe9, 0x5f, 0xf5, 0xf6, 0x2f, 0x31, 0xf3, 0x7c, 0x12,
	0x7e, 0xe6, 0xe3, 0x88, 0xb9, 0x97, 0x24, 0xfc, 0xcc, 0xe5, 0xc1, 0xbe, 0x1b, 0x78, 0xfb, 0x83,
	0x27, 0xea, 0x67, 0xaf, 0x1f, 0x72, 0xc9, 0xd1, 0x47, 0x57, 0xd1, 0x39, 0x19, 0xd0, 0x50, 0xee,
	0xa9, 0xb9, 0xc1, 0x13, 0xfb, 0x02, 0xd6, 0xbe, 0x23, 0x41, 0x74, 0x46, 0x42, 0x41, 0x39, 0x73,
	0x88, 0xe8, 0x73, 0x26, 0x08, 0xfa, 0x02, 0x6a, 0xa1, 0x79, 0xb6, 0x4a, 0x3b, 0xa5, 0xdd, 0xa5,
	0xa7, 0x5b, 0x7b, 0x13, 0xa6, 0x7b, 0x89, 0xb2, 0x33, 0x52, 0x45, 0x16, 0x2c, 0x0e, 0x62, 0x24,
	0xab, 0xbc, 0x53, 0xda, 0xad, 0x3b, 0xc9, 0xd0, 0x7e, 0x04, 0x95, 0xb3, 0xf6, 0xb1, 0x56, 0x08,
	0xe8, 0x37, 0x82, 0x33, 0x0d, 0xbb, 0xec, 0x24, 0x43, 0xfb, 0x09, 0x54, 0x1a, 0x9d, 0x53, 0xb4,
	0x0a, 0x65, 0xea, 0x69, 0xd9, 0x8a, 0x53, 0xa6, 0x1e, 0xda, 0x86, 0x9a, 0xa0, 0xe7, 0x3e, 0x65,
	0x3d, 0x61, 0x95, 0x77, 0x2a, 0xbb, 0x2b, 0xce, 0x68, 0x6c, 0xef, 0xc3, 0x62, 0x37, 0x7e, 0xce,
	0x98, 0xad, 0xc3, 0xfc, 0x00, 0xfb, 0x11, 0xd1, 0x61, 0x54, 0x9d, 0x78, 0x60, 0xb7, 0x60, 0xbe,
	0x83, 0x7b, 0x44, 0x28, 0xb1, 0xcb, 0x23, 0x26, 0xb5, 0x45, 0xd5, 0x89, 0x07, 0x08, 0x41, 0x35,
	0x62, 0x54, 0x9a, 0xd0, 0xf5, 0xb3, 0x9a, 0x13, 0xf4, 0x67, 0x62, 0x55, 0x34, 0xb4, 0x7e, 0xb6,
	0x9f, 0xc1, 0x42, 0x9b, 0x04, 0x3c, 0x1c, 0xa2, 0x4d, 0x58, 0xc0, 0x41, 0x0a, 0xc8, 0x8c, 0xf2,
	0x90, 0xec, 0xff, 0x94, 0xa0, 0xda, 0x20, 0xbe, 0x9f, 0x89, 0x75, 0x1f, 0x16, 0x02, 0x0d, 0xa7,
	0xd5, 0x97, 0x9e, 0x7e, 0x9c, 0xd9, 0xe9, 0xd8, 0x9b, 0x63, 0xd4, 0xd0, 0xa7, 0x30, 0xdf, 0x57,
	0xcb, 0xb0, 0x2a, 0x3b, 0x95, 0xdd, 0xa5, 0xa7, 0x9b, 0x19, 0x7d, 0xbd, 0x48, 0x27, 0x56, 0x42,
	0xcf, 0xa1, 0xee, 0x51, 0x21, 0x31, 0x73, 0x89, 0xb0, 0xaa, 0xda, 0xc2, 0xca, 0x58, 0x98, 0x7d,
	0x74, 0xae, 0x55, 0xd1, 0x2e, 0x54, 0xdd, 0x7e, 0x24, 0xac, 0x79, 0x6d, 0xb2, 0x9e, 0x31, 0x69,
	0x74, 0x4e, 0x1d, 0xad, 0x61, 0xbf, 0x84, 0xda, 0x09, 0xef, 0x73, 0x9f, 0xf7, 0x86, 0xe8, 0x19,
	0x00, 0x8b, 0x02, 0xfc, 0xa3, 0x4b, 0x7c, 0x5f, 0x58, 0x25, 0x6d, 0xbb, 0x91, 0xb5, 0x25, 0xbe,
	0xef, 0xd4, 0x95, 0xa2, 0x7a, 0x12, 0xf6, 0x3f, 0x4b, 0xb0, 0xd0, 0x6d, 0x1f, 0x50, 0x2e, 0x90,
	0x0d, 0xcb, 0x01, 0x66, 0xd1, 0x05, 0x76, 0x65, 0x14, 0x92, 0x50, 0xef, 0x53, 0xdd, 0x19, 0x9b,
	0x53, 0x59, 0xd4, 0x0f, 0xb9, 0x17, 0xb9, 0xc9, 0x0e, 0x27, 0xc3, 0x74, 0x02, 0x56, 0xc6, 0x12,
	0x10, 0xdd, 0x83, 0x8a, 0xb8, 0x8a, 0xac, 0xaa, 0x9e, 0x55, 0x8f, 0xea, 0xf0, 0x2e, 0x70, 0x40,
	0xfd, 0xa1, 0x35, 0xaf, 0x27, 0xcd, 0xc8, 0xfe, 0x47, 0x09, 0x6a, 0x4d, 0x2a, 0xae, 0x8e, 0xd9,
	0x05, 0xd7, 0x4a, 0x3c, 0x0c, 0xb0, 0x34, 0x81, 0x98, 0x11, 0xda, 0x81, 0xa5, 0x73, 0xec, 0x5e,
	0x51, 0xd6, 0x3b, 0xa4, 0x3e, 0x31, 0x61, 0xa4, 0xa7, 0xd0, 0x43, 0x00, 0x15, 0x2f, 0xf6, 0xbb,
	0x49, 0xfe, 0x54, 0x9d, 0xd4, 0x8c, 0x42, 0x50, 0x5b, 0x92, 0x28, 0x54, 0xb5, 0x42, 0x7a, 0xca,
	0xfe, 0x77, 0x19, 0x56, 0x1a, 0x7e, 0x24, 0x24, 0x09, 0x1b, 0x9c, 0x5d, 0xd0, 0x1e, 0xda, 0x03,
	0xd4, 0x7a, 0xdf, 0xc7, 0xcc, 0x53, 0xf1, 0x89, 0x16, 0xc3, 0xe7, 0x3e, 0x89, 0x53, 0xa9, 0xe6,
	0xe4, 0x48, 0xd0, 0x1f, 0x61, 0xeb, 0x30, 0x24, 0x44, 0xe5, 0x83, 0x43, 0xfa, 0x3c, 0x94, 0x94,
	0xf5, 0x9a, 0x54, 0xc4, 0x66, 0x65, 0x6d, 0x56, 0xac, 0x80, 0x5e, 0x80, 0x75, 0xc0, 0xdd, 0x4b,
	0xd1, 0xa4, 0xa2, 0xef, 0xe3, 0xe1, 0x21, 0x0f, 0x5b, 0x87, 0xc7, 0x47, 0x11, 0x11, 0x52, 0xe8,
	0xf5, 0xd4, 0x9c, 0x42, 0xb9, 0xb2, 0xed, 0x92, 0x90, 0x62, 0xbf, 0xc1, 0x99, 0xe0, 0x3e, 0x79,
	0xc5, 0xaf, 0x1d, 0x57, 0x63, 0xdb, 0x22, 0x39, 0x7a, 0x0e, 0x9b, 0x4d, 0xfe, 0x8e, 0xbd, 0xc3,
	0xa1, 0xd7, 0x26, 0x32, 0xa4, 0xee, 0x68, 0xa5, 0xf3, 0xda, 0xb2, 0x40, 0x6a, 0x7f, 0x0e, 0x5b,
	0xc7, 0x4c, 0x92, 0xf0, 0x02, 0xbb, 0xe4, 0x80, 0x32, 0x8f, 0xb2, 0x5e, 0x9b, 0xf6, 0x42, 0x2c,
	0xd5, 0xf9, 0x6f, 0xaa, 0xa2, 0x95, 0x97, 0xdc, 0x4b, 0x0e, 0x32, 0x1e, 0xd9, 0xff, 0x5d, 0x84,
	0x8d, 0xb3, 0x78, 0xd3, 0xdb, 0xd8, 0xbd, 0xa4, 0x8c, 0xbc, 0xe9, 0x2b, 0x03, 0x81, 0xbe, 0x85,
	0xf5, 0x71, 0x41, 0x9c, 0xa1, 0xa6, 0x1f, 0x66, 0xab, 0x34, 0x16, 0x3b, 0xb9, 0x46, 0xe8, 0x19,
	0x6c, 0xb4, 0x49, 0x70, 0x80, 0x7d, 0x9f, 0x73, 0xd6, 0x95, 0x58, 0x8a, 0x0e, 0x09, 0x29, 0x8f,
	0x4f, 0x61, 0xc5, 0xc9, 0x17, 0xa2, 0xdf, 0xc3, 0x5a, 0x27, 0x24, 0x6a, 0xde, 0xc5, 0x92, 0x78,
	0x67, 0xdc, 0x8f, 0x02, 0x53, 0xf7, 0x75, 0x27, 0x4f, 0xa4, 0x1a, 0xb7, 0x34, 0xb5, 0xa8, 0xf7,
	0x39, 0xaf, 0x71, 0x27, 0xc5, 0xea, 0x8c, 0x54, 0x51, 0x17, 0xea, 0x3a, 0x71, 0x54, 0xce, 0x9b,
	0x8a, 0xff, 0x22, 0x63, 0x97, 0xbb, 0x4d, 0x7b, 0x23, 0xbb, 0x16, 0x93, 0xe1, 0xd0, 0xb9, 0xc6,
	0x29, 0xc8, 0xd6, 0x85, 0xc2, 0x6c, 0x6d, 0xc2, 0x8a, 0x9b, 0x4e, 0x77, 0x6b, 0x51, 0x2f, 0xe0,
	0x61, 0xb6, 0x7d, 0xa4, 0xb5, 0x9c, 0x71, 0x23, 0xf4, 0x4b, 0x09, 0xb6, 0x68, 0x92, 0x06, 0x4d,
	0x1e, 0x60, 0xca, 0xbe, 0x92, 0x12, 0xbb, 0x97, 0x01, 0x61, 0xd2, 0xaa, 0xe9, 0xb5, 0xb5, 0x3e,
	0x70, 0x6d, 0xc7, 0x45, 0x38, 0xf1, 0x5a, 0x8b, 0xfd, 0x20, 0x06, 0x68, 0x24, 0x1c, 0x25, 0xa1,
	0x55, 0xd7, 0xde, 0xbf, 0xbc, 0xab, 0xf7, 0x11, 0x40, 0xec, 0x36, 0x07, 0x79, 0xfb, 0x2d, 0xac,
	0x8e, 0x1f, 0x84, 0x6a, 0x78, 0x57, 0x64, 0x68, 0xb2, 0x5d, 0x3d, 0xa2, 0xfd, 0xf4, 0xa5, 0x98,
	0x97, 0x18, 0x49, 0xd7, 0x33, 0xf7, 0xe5, 0x8b, 0xf2, 0x1f, 0x4a, 0xdb, 0xaf, 0xe0, 0xe1, 0xcd,
	0xbb, 0x90, 0xe3, 0x68, 0xec, 0xf6, 0xad, 0xa7, 0xd1, 0x7e, 0x82, 0x8f, 0x0b, 0x56, 0x95, 0x03,
	0xf3, 0x72, 0x3c, 0xde, 0xdf, 0x65, 0xe2, 0x2d, 0xac, 0xf6, 0x94, 0x4b, 0x7b, 0x00, 0x70, 0xd6,
	0x3e, 0x76, 0xc8, 0x4f, 0xaa, 0x31, 0xa1, 0xc7, 0x50, 0x19, 0x04, 0xd4, 0xd4, 0x70, 0xf6, 0x52,
	0x53, 0x9a, 0x4a, 0x01, 0xbd, 0x84, 0x45, 0x1e, 0x1f, 0x83, 0xf1, 0xfe, 0xf8, 0xc3, 0x0e, 0xcd,
	0x49, 0xcc, 0xec, 0x13, 0xb8, 0x77, 0x1d, 0xcf, 0x1d, 0xbd, 0x5b, 0xe3, 0xde, 0x97, 0xaf, 0x51,
	0x7f, 0x29, 0xc1, 0x52, 0xeb, 0x3d, 0x71, 0x13, 0xc4, 0x87, 0x00, 0x9e, 0x3e, 0x95, 0xd7, 0x38,
	0x20, 0x66, 0xf3, 0x52, 0x33, 0x0a, 0xa9, 0xc1, 0x83, 0x00, 0x33, 0x2f, 0xb9, 0x2a, 0xcd, 0x50,
	0x71, 0x94, 0xaf, 0xc2, 0x5e, 0xd2, 0x4c, 0xf4, 0x33, 0x7a, 0x0c, 0xab, 0x92, 0x06, 0x84, 0x47,
	0xb2, 0x4b, 0x5c, 0xce, 0x3c, 0xa1, 0x7b, 0xc8, 0xbc, 0x33, 0x31, 0x6b, 0xaf, 0xc2, 0x72, 0x2b,
	0xe8, 0xcb, 0xa1, 0x89, 0xc2, 0xfe, 0x12, 0x6a, 0x4e, 0x8a, 0x03, 0x8a, 0xc8, 0x75, 0x89, 0x10,
	0xe6, 0x62, 0x4a, 0x86, 0x4a, 0x12, 0x10, 0x21, 0x70, 0x2f, 0x49, 0x8c, 0x64, 0x68, 0xff, 0x08,
	0xab, 0x71, 0x6e, 0x4d, 0x4b, 0x40, 0x37, 0x61, 0x21, 0x5e, 0xbc, 0xf1, 0x60, 0x46, 0x36, 0x83,
	0xb5, 0xd8, 0x81, 0xee, 0xae, 0xd3, 0x7a, 0xd9, 0x81, 0x25, 0xef, 0x1a, 0x2d, 0xb9, 0xfc, 0x53,
	0x53, 0xf6, 0x7b, 0xb8, 0xaf, 0x2f, 0x42, 0x5d, 0x4d, 0x53, 0x7a, 0xfb, 0x14, 0xee, 0xf7, 0x26,
	0xb1, 0x8c, 0xcf, 0xac, 0xc0, 0xfe, 0x7b, 0x09, 0x36, 0xb4, 0xeb, 0x53, 0x41, 0xc2, 0x57, 0x54,
	0xc8, 0x69, 0xdd, 0x3f, 0x83, 0x8d, 0x5e, 0x1e, 0x9e, 0x09, 0x21, 0x5f, 0x68, 0xff, 0xab, 0x04,
	0x96, 0x0e, 0x43, 0x71, 0x21, 0x31, 0x14, 0x92, 0x04, 0x53, 0x6f, 0xfb, 0x0b, 0xb0, 0x7a, 0x05,
	0x90, 0x26, 0x98, 0x42, 0xb9, 0x3d, 0x84, 0xe5, 0xb8, 0x6c, 0xa6, 0x0b, 0x61, 0x1b, 0x6a, 0xe4,
	0x3d, 0x95, 0x0d, 0xee, 0xc5, 0x2e, 0xe7, 0x9d, 0xd1, 0x58, 0xe5, 0x9e, 0x90, 0xde, 0x9b, 0x48,
	0x1a, 0xea, 0x69, 0x46, 0xf6, 0xf7, 0x70, 0x4f, 0xef, 0x44, 0x47, 0x11, 0xec, 0x0f, 0x2c, 0xdb,
	0x6c, 0x21, 0x96, 0x73, 0x0b, 0xf1, 0x1b, 0x93, 0x67, 0x31, 0xf6, 0x54, 0x6b, 0xb3, 0x39, 0xac,
	0x28, 0x2e, 0xf8, 0x33, 0xb9, 0x6b, 0xb7, 0x7a, 0x0e, 0x9b, 0x11, 0xbb, 0xd0, 0xa6, 0x27, 0x79,
	0x41, 0x17, 0x48, 0xed, 0xb7, 0x70, 0x3f, 0x7e, 0xb3, 0x69, 0x46, 0x41, 0xff, 0xae, 0x4e, 0xb7,
	0xa1, 0xe6, 0x45, 0x41, 0xbf, 0x83, 0xe5, 0xa5, 0x39, 0xfc, 0xd1, 0xd8, 0x3e, 0x87, 0x8f, 0xba,
	0xad, 0xb3, 0x59, 0xd4, 0x9e, 0x6a, 0x66, 0x64, 0xa0, 0x59, 0x91, 0x69, 0xc4, 0x66, 0x68, 0xff,
	0xad, 0x04, 0x5b, 0xaf, 0xf4, 0xbb, 0x76, 0x9b, 0x60, 0x11, 0x85, 0x44, 0x5d, 0x88, 0x33, 0x28,
	0x75, 0x7f, 0x12, 0xd3, 0x38, 0xce, 0x0a, 0xec, 0x1f, 0x14, 0xdf, 0xfd, 0x2b, 0x71, 0x65, 0x1c,
	0x47, 0x97, 0xb8, 0x21, 0x91, 0x33, 0xbb, 0x6a, 0x9e, 0xfe, 0x6f, 0x0d, 0x2a, 0x8d, 0xc0, 0x43,
	0xaf, 0x01, 0x75, 0x87, 0xcc, 0x1d, 0xbf, 0xee, 0xd0, 0xaf, 0x72, 0x21, 0x63, 0xe7, 0xdb, 0xc5,
	0x8b, 0xb5, 0xe7, 0xd0, 0x1b, 0x58, 0xeb, 0xe0, 0x48, 0x90, 0x99, 0x01, 0x7e, 0x07, 0x1b, 0xa7,
	0xac, 0x3f, 0x53, 0xc8, 0x2e, 0xac, 0xc7, 0xb5, 0x30, 0x81, 0x98, 0xe5, 0xa2, 0x63, 0x25, 0x73,
	0x33, 0xa8, 0x03, 0x9b, 0xa7, 0xa6, 0x12, 0x66, 0x16, 0xe8, 0x09, 0x58, 0x5d, 0x7e, 0x21, 0x1d,
	0x72, 0xce, 0xb9, 0x9c, 0x19, 0xaa, 0x03, 0x9b, 0xdd, 0xcb, 0x48, 0x7a, 0xfc, 0x1d, 0x9b, 0x19,
	0xe6, 0x6b, 0x40, 0xdf, 0x52, 0xdf, 0x9f, 0x19, 0x5e, 0x07, 0xd6, 0x9b, 0xc4, 0x27, 0x72, 0x76,
	0x7b, 0xf9, 0x16, 0x36, 0x62, 0xc6, 0x36, 0x09, 0xf9, 0x9b, 0xec, 0x17, 0x99, 0x09, 0x66, 0x77,
	0x6b, 0xc6, 0xab, 0x0a, 0x1a, 0x19, 0x9d, 0xe0, 0xb0, 0x47, 0xe4, 0x14, 0x91, 0xfe, 0x09, 0x1e,
	0x34, 0x30, 0x73, 0xc9, 0xc4, 0x6e, 0x5e, 0xbf, 0xed, 0x4e, 0x77, 0xf4, 0xb4, 0xc7, 0xb0, 0x1f,
	0x07, 0xd9, 0xe1, 0x5e, 0xc3, 0x27, 0x98, 0x45, 0xfd, 0x29, 0x30, 0xff, 0x0c, 0x8f, 0x0e, 0x29,
	0xc3, 0x3e, 0x9d, 0x4c, 0xfc, 0x59, 0x04, 0xfc, 0x1a, 0xd0, 0xd7, 0x5c, 0xf6, 0xfd, 0xa8, 0xf7,
	0x35, 0x17, 0xb2, 0x49, 0x06, 0xd4, 0x25, 0x62, 0x0a, 0xbc, 0x36, 0xd4, 0x8f, 0x88, 0x8c, 0xd9,
	0x22, 0x7a, 0x90, 0xd1, 0x4c, 0xf3, 0xde, 0xed, 0x47, 0xd9, 0x57, 0xa8, 0x31, 0x1a, 0xab, 0x93,
	0x6a, 0x75, 0x04, 0xa7, 0xb9, 0xe1, 0x6d, 0x98, 0xbf, 0x2d, 0xc0, 0x1c, 0x63, 0xae, 0xba, 0x45,
	0x2d, 0x1f, 0x11, 0x39, 0x62, 0x99, 0xb7, 0xc1, 0xda, 0x19, 0x71, 0x86, 0xa0, 0x6a, 0xd0, 0xda,
	0x11, 0xd1, 0x6c, 0xee, 0xd6, 0x38, 0x1f, 0xe7, 0x03, 0x66, 0x98, 0xe0, 0x1c, 0xfa, 0x8b, 0xde,
	0x82, 0x14, 0x2b, 0xbb, 0x0d, 0xfa, 0x93, 0x7c, 0xe8, 0x3c, 0x5e, 0x37, 0x87, 0x0e, 0xa0, 0xaa,
	0xd8, 0xcf, 0x6d, 0x98, 0x37, 0x9e, 0x79, 0x0b, 0xaa, 0x8a, 0x1d, 0xa2, 0x5f, 0x67, 0x31, 0xae,
	0xdf, 0xb5, 0xb6, 0x1f, 0x14, 0x48, 0x53, 0xcd, 0xb8, 0x3e, 0x62, 0x63, 0x39, 0x4d, 0x63, 0x92,
	0x05, 0x16, 0x9d, 0x49, 0x9a, 0xcc, 0xe9, 0xea, 0xb1, 0x26, 0xaa, 0x66, 0x44, 0x9a, 0x90, 0x5d,
	0xf0, 0xad, 0x38, 0xc5, 0xa8, 0x6e, 0xeb, 0x79, 0xea, 0x6c, 0x52, 0x7f, 0x01, 0xdc, 0x3d, 0x3d,
	0x73, 0xfe, 0x3f, 0x30, 0x7d, 0x24, 0xc3, 0x1a, 0x1a, 0x9d, 0x53, 0x31, 0xe5, 0x65, 0x97, 0xc1,
	0x34, 0x9f, 0xe2, 0xa7, 0xe1, 0x23, 0x70, 0x44, 0xa4, 0x21, 0x8c, 0xb7, 0x2d, 0x7f, 0x27, 0xfb,
	0xd9, 0x6f, 0x9c, 0x69, 0xda, 0x73, 0x08, 0xc3, 0xfa, 0x11, 0x91, 0x19, 0x72, 0x78, 0x73, 0x88,
	0xd9, 0xaf, 0x1b, 0x85, 0xec, 0xd2, 0x9e, 0x43, 0x3f, 0x00, 0xca, 0x52, 0x3f, 0x94, 0xf7, 0x85,
	0xa4, 0x80, 0x1f, 0xde, 0xb8, 0x25, 0x07, 0xd5, 0xef, 0xcb, 0x83, 0x27, 0xe7, 0x0b, 0xfa, 0x3f,
	0xa3, 0xcf, 0xff, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x69, 0xd5, 0xb9, 0xc0, 0x60, 0x1a, 0x00, 0x00,
}
