/*
Copyright The KubeVirt Authors.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"
	v1beta1 "kubevirt.io/api/pool/v1beta1"
	poolv1beta1 "kubevirt.io/client-go/kubevirt/typed/pool/v1beta1"
)

// fakeVirtualMachinePools implements VirtualMachinePoolInterface
type fakeVirtualMachinePools struct {
	*gentype.FakeClientWithList[*v1beta1.VirtualMachinePool, *v1beta1.VirtualMachinePoolList]
	Fake *FakePoolV1beta1
}

func newFakeVirtualMachinePools(fake *FakePoolV1beta1, namespace string) poolv1beta1.VirtualMachinePoolInterface {
	return &fakeVirtualMachinePools{
		gentype.NewFakeClientWithList[*v1beta1.VirtualMachinePool, *v1beta1.VirtualMachinePoolList](
			fake.Fake,
			namespace,
			v1beta1.SchemeGroupVersion.WithResource("virtualmachinepools"),
			v1beta1.SchemeGroupVersion.WithKind("VirtualMachinePool"),
			func() *v1beta1.VirtualMachinePool { return &v1beta1.VirtualMachinePool{} },
			func() *v1beta1.VirtualMachinePoolList { return &v1beta1.VirtualMachinePoolList{} },
			func(dst, src *v1beta1.VirtualMachinePoolList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.VirtualMachinePoolList) []*v1beta1.VirtualMachinePool {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta1.VirtualMachinePoolList, items []*v1beta1.VirtualMachinePool) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
