DOCKER_PREFIX=${DOCKER_PREFIX:-"quay.io/kubevirt"}
DOCKER_IMAGE=${DOCKER_IMAGE:-"builder"}
DOCKER_CROSS_IMAGE=${DOCKER_CROSS_IMAGE:-"builder-cross"}
DOCKER_CS10_IMAGE=${DOCKER_CS10_IMAGE:-"builder-cs10"}
DOCKER_CS10_CROSS_IMAGE=${DOCKER_CS10_CROSS_IMAGE:-"builder-cs10-cross"}

ARCHITECTURES=${ARCHITECTURES:-"amd64 arm64 s390x"}
