#!/bin/bash

KUBEVIRT_VERSION="v0.40.0-rc.2"
CDI_VERSION="v1.33.1"
NETWORK_ADDONS_VERSION="v0.51.0"
SSP_VERSION="v0.2.0-rc.1"
NMO_VERSION="v0.7.0"
HPPO_VERSION="v0.7.2"
HPP_VERSION="v0.7.1"
CONVERSION_CONTAINER_VERSION="v2.0.0"
VMWARE_CONTAINER_VERSION="v2.0.0-9"
VM_IMPORT_VERSION="v0.3.4"

CONTAINER_REGISTRY="quay.io/kubevirt"

RELEASE_DELTA="${RELEASE_DELTA:-0}"

PACKAGE_DIR="./deploy/olm-catalog/community-kubevirt-hyperconverged"
CSV_VERSION=$(ls -d ${PACKAGE_DIR}/*/ | sort -rV | awk "NR==$((RELEASE_DELTA+1))" | cut -d '/' -f 5)
REPLACES_CSV_VERSION=$(ls -d ${PACKAGE_DIR}/*/ | sort -rV | awk "NR==$((RELEASE_DELTA+2))" | cut -d '/' -f 5)
