#!/bin/bash

KUBEVIRT_VERSION="v0.48.0-rc.0"
CDI_VERSION="v1.41.1"
NETWORK_ADDONS_VERSION="v0.63.0"
SSP_VERSION="v0.13.0-rc.2"
NMO_VERSION="v0.10.0"
HPPO_VERSION="v0.11.0"
HPP_VERSION="v0.11.0"

CONTAINER_REGISTRY="quay.io/kubevirt"

RELEASE_DELTA="${RELEASE_DELTA:-0}"

PACKAGE_DIR="./deploy/olm-catalog/community-kubevirt-hyperconverged"
CSV_VERSION=$(ls -d ${PACKAGE_DIR}/*/ | sort -rV | awk "NR==$((RELEASE_DELTA+1))" | cut -d '/' -f 5)
REPLACES_CSV_VERSION=$(ls -d ${PACKAGE_DIR}/*/ | sort -rV | awk "NR==$((RELEASE_DELTA+2))" | cut -d '/' -f 5)
