#!/usr/bin/env bash
# Generates centos_stream_alias() calls for all rpmtree targets
# This script should be run after both CS9 and CS10 RPMs have been generated

set -ex

source hack/common.sh

# List of base target names (without _cs9/_cs10 suffix)
TARGETS=(
    "testimage_x86_64"
    "testimage_aarch64"
    "testimage_s390x"
    "libvirt-devel_x86_64"
    "libvirt-devel_aarch64"
    "libvirt-devel_s390x"
    "sandboxroot_x86_64"
    "sandboxroot_aarch64"
    "sandboxroot_s390x"
    "launcherbase_x86_64"
    "launcherbase_aarch64"
    "launcherbase_s390x"
    "handlerbase_x86_64"
    "handlerbase_aarch64"
    "handlerbase_s390x"
    "passt_tree_x86_64"
    "passt_tree_aarch64"
    "passt_tree_s390x"
    "libguestfs-tools_x86_64"
    "libguestfs-tools_s390x"
    "exportserverbase_x86_64"
    "exportserverbase_aarch64"
    "exportserverbase_s390x"
    "pr-helper_x86_64"
    "pr-helper_aarch64"
    "sidecar-shim_x86_64"
    "sidecar-shim_aarch64"
    "sidecar-shim_s390x"
    "libnbd-devel_x86_64"
    "libnbd-devel_aarch64"
    "libnbd-devel_s390x"
)

LIBVIRT_PATHS=(
    "usr/lib64"
    "usr/include/libvirt"
)

LIBNBD_PATHS=(
    "usr/lib64"
    "usr/include"
)

ARCHITECTURES=(
    "x86_64"
    "aarch64"
    "s390x"
)

BUILD_FILE="${KUBEVIRT_DIR}/rpm/BUILD.bazel"

# Remove existing aliases section if present
if grep -q "^# CentOS Stream version-selecting aliases" "${BUILD_FILE}"; then
    awk '
    BEGIN { skipping = 0 }
    /^# CentOS Stream version-selecting aliases/ { skipping = 1; next }
    /^# End of CentOS Stream version-selecting aliases/ { skipping = 0; next }
    skipping && /^(# CentOS Stream .* targets|rpmtree\(|tar2files\(|bazeldnf\()/ { skipping = 0 }
    !skipping { print }
    ' "${BUILD_FILE}" >"${BUILD_FILE}.tmp"
    mv "${BUILD_FILE}.tmp" "${BUILD_FILE}"
fi

# Append alias definitions
cat >>"${BUILD_FILE}" <<'HEADER'

# CentOS Stream version-selecting aliases
# Auto-generated by hack/rpm-deps-aliases.sh - do not edit manually

HEADER

for target in "${TARGETS[@]}"; do
    cat >>"${BUILD_FILE}" <<EOF
centos_stream_alias(
    name = "${target}",
    cs9_target = ":${target}_cs9",
    cs10_target = ":${target}_cs10",
    visibility = ["//visibility:public"],
)

EOF
done

# Path-based aliases for libvirt-libs tar2files outputs
# These are used by the main BUILD.bazel cc_library
cat >>"${BUILD_FILE}" <<'HEADER'
# Path-based aliases for libvirt-libs tar2files outputs
HEADER

for arch in "${ARCHITECTURES[@]}"; do
    for path in "${LIBVIRT_PATHS[@]}"; do
        cat >>"${BUILD_FILE}" <<EOF
centos_stream_alias(
    name = "libvirt-libs_${arch}/${path}",
    cs9_target = ":libvirt-libs_${arch}_cs9/${path}",
    cs10_target = ":libvirt-libs_${arch}_cs10/${path}",
    visibility = ["//visibility:public"],
)

EOF
    done
done

# Path-based aliases for libnbd-libs tar2files outputs
cat >>"${BUILD_FILE}" <<'HEADER'
# Path-based aliases for libnbd-libs tar2files outputs
HEADER

for arch in "${ARCHITECTURES[@]}"; do
    for path in "${LIBNBD_PATHS[@]}"; do
        cat >>"${BUILD_FILE}" <<EOF
centos_stream_alias(
    name = "libnbd-libs_${arch}/${path}",
    cs9_target = ":libnbd-libs_${arch}_cs9/${path}",
    cs10_target = ":libnbd-libs_${arch}_cs10/${path}",
    visibility = ["//visibility:public"],
)

EOF
    done
done

cat >>"${BUILD_FILE}" <<'FOOTER'
# End of CentOS Stream version-selecting aliases
FOOTER

echo "Generated centos_stream_alias targets in ${BUILD_FILE}"
