apiVersion: kubevirt.io/v1alpha1
kind: VirtualMachineReplicaSet
metadata:
  name: testreplicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      myvm: "myvm"
  template:
    metadata:
      name: test
      labels:
        myvm: "myvm"
    spec:
      domain:
        resources:
          initial:
            memory: 64M
        devices:
          disks:
          - name: registrydisk
            volumeName: registryvolume
            disk:
              dev: vda
      volumes:
        - name: registryvolume
          registryDisk:
            image: kubevirt/cirros-registry-disk-demo:devel
