metadata:
  name: atomic-ephemeral
  namespace: kubevirt-demo
apiVersion: kubevirt.io/v1alpha1
kind: VirtualMachine
spec:
  terminationGracePeriodSeconds: 0
  domain:
    devices:
      disks:
      - type: RegistryDisk:v1alpha
        source:
          name: kubevirt/fedora-atomic-registry-disk-demo:devel
        target:
          dev: vda
      - type: file
        target:
          dev: vdb
        cloudinit:
            nocloud:
                userDataBase64: I2Nsb3VkLWNvbmZpZwpwYXNzd29yZDogYXRvbWljCnNzaF9wd2F1dGg6IFRydWUKY2hwYXNzd2Q6IHsgZXhwaXJlOiBGYWxzZSB9Cg==
      interfaces:
      - source:
          network: default
        type: network
    memory:
      unit: MB
      value: 1024
    os:
      type:
        os: hvm
    type: qemu
