apiVersion: v1
kind: Template
metadata:
  name: windows2012r2-vm-template
  console.openshift.io/iconClass: icon-windows
  annotations:
    description: "OCP KubeVirt Microsoft Windows Server 2012 R2 VM template"
    tags: "kubevirt,ocp,template,windows,virtualmachine"
  labels:
    kubevirt.io/os: win2k12r2
    miq.github.io/kubevirt-is-vm-template: "true"
objects:
- apiVersion: kubevirt.io/v1alpha1
  kind: StatefulVirtualMachine
  metadata:
    name: ${NAME}
    labels:
      kubevirt-svm: svm-${NAME}
  spec:
    template:
      metadata:
        labels:
          kubevirt-svm: svm-${NAME}
      spec:
        domain:
          features:
            acpi: {}
            apic: {}
            hyperv:
              relaxed: {}
              vapic: {}
              spinlocks:
                spinlocks: 8191
          clock:
            utc: {}
            timer:
              hpet:
                present: false
              pit:
                tickPolicy: delay
              rtc:
                tickPolicy: catchup
              hyperv: {}
          cpu:
            cores: ${{CPU_CORES}}
          machine:
            type: q35
          resources:
            requests:
              memory: ${{MEMORY}}
          devices:
            disks:
              - name: disk0
                volumeName: disk0-pvc
        volumes:
          - name: disk0-pvc
            persistentVolumeClaim:
              claimName: windows-vm-pvc-${NAME}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: windows-vm-pvc-${NAME}
    #FIXME: add an annotation to specify which volume this pvc should be based on
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
parameters:
- name: NAME
  description: Name for the new VM
- name: MEMORY
  description: Amount of memory
  value: 4096Mi
- name: CPU_CORES
  description: Amount of cores
  value: "4"
