apiVersion: v1
kind: Template
metadata:
  name: windows2012r2-vm-template
  annotations:
    description: "OCP KubeVirt Microsoft Windows Server 2012 R2 VM template"
    tags: "kubevirt,ocp,template,windows"
  labels:
    kubevirt.io/os: win2k12r2
    miq.github.io/kubevirt-is-vm-template: "true"
objects:
- apiVersion: kubevirt.io/v1alpha1
  kind: OfflineVirtualMachine
  metadata:
    name: ${NAME}
    labels:
      kubevirt.io/ovm: ovm-${NAME}
  spec:
    template:
      metadata:
        labels:
          kubevirt.io/ovm: ovm-${NAME}
      spec:
        domain:
          features:
            acpi: {}
            apic: {}
            hyperv:
              relaxed: {}
              vapic: {}
              spinlocks:
                spinlocks: 8191
          clock:
            utc: {}
            timer:
              hpet:
                present: false
              pit:
                tickPolicy: delay
              rtc:
                tickPolicy: catchup
              hyperv: {}
          cpu:
            cores: ${{CPU_CORES}}
          machine:
            type: q35
          resources:
            requests:
              memory: ${{MEMORY}}
          devices:
            disks:
              - name: disk0
                volumeName: disk0-pvc
        volumes:
          - name: disk0-pvc
            persistentVolumeClaim:
              claimName: ${PVC_NAME}
parameters:
- name: NAME
  description: Name for the new VM
- name: MEMORY
  description: Amount of memory
  value: 4096Mi
- name: CPU_CORES
  description: Amount of cores
  value: "4"
- name: PVC_NAME
  description: PVC to use
