apiVersion: v1
kind: Template
metadata:
  name: rhel7-vm-template
  console.openshift.io/iconClass: icon-rhel
  annotations:
    description: "OCP KubeVirt Red Hat Enterprise Linux 7.4 VM template"
    tags: "kubevirt,ocp,template,linux,virtualmachine"
  labels:
    kubevirt.io/os: rhel7.4
    miq.github.io/kubevirt-is-vm-template: "true"
objects:
- apiVersion: kubevirt.io/v1alpha1
  kind: StatefulVirtualMachine
  metadata:
    name: ${NAME}
    labels:
      kubevirt-svm: svm-${NAME}
  spec:
    template:
      metadata:
        labels:
          kubevirt-svm: svm-${NAME}
      spec:
        domain:
          cpu:
            cores: ${{CPU_CORES}}
          resources:
            requests:
              memory: ${{MEMORY}}
          machine:
            type: q35
          devices:
            disks:
              - name: disk0
                volumeName: disk0-pvc
                disk:
                  dev: vda
        volumes:
          - name: disk0-pvc
            persistentVolumeClaim:
              claimName: linux-vm-pvc-${NAME}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: linux-vm-pvc-${NAME}
    #FIXME: add an annotation to specify which volume this pvc should be based on
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
parameters:
- name: NAME
  description: Name for the new VM
- name: MEMORY
  description: Amount of memory
  value: 4096Mi
- name: CPU_CORES
  description: Amount of cores
  value: "4"
