apiVersion: v1
kind: Template
metadata:
  name: fedora-vm-template
  console.openshift.io/iconClass: icon-fedora
  annotations:
    description: "OCP KubeVirt Fedora 27 VM template"
    tags: "kubevirt,ocp,template,linux"
  labels:
    kubevirt.io/os: fedora27
    miq.github.io/kubevirt-is-vm-template: "true"
objects:
- apiVersion: kubevirt.io/v1alpha1
  kind: OfflineVirtualMachine
  metadata:
    name: ${NAME}
    labels:
      kubevirt-ovm: ovm-${NAME}
  spec:
    template:
      metadata:
        labels:
          kubevirt-ovm: ovm-${NAME}
      spec:
        domain:
          cpu:
            cores: ${{CPU_CORES}}
          resources:
            requests:
              memory: ${{MEMORY}}
          devices:
            disks:
              - name: disk0
                volumeName: registryvolume
                disk:
                  bus: virtio
              - name: disk1
                volumeName: cloudinitvolume
                disk:
                  bus: virtio
        volumes:
          - name: registryvolume
            registryDisk:
              image: kubevirt/fedora-cloud-registry-disk-demo:devel
          - name: cloudinitvolume
            cloudInitNoCloud:
              userDataBase64: I2Nsb3VkLWNvbmZpZwpwYXNzd29yZDogYXRvbWljCnNzaF9wd2F1dGg6IFRydWUKY2hwYXNzd2Q6IHsgZXhwaXJlOiBGYWxzZSB9Cg==
parameters:
- name: NAME
  description: Name for the new VM
- name: MEMORY
  description: Amount of memory
  value: 4096Mi
- name: CPU_CORES
  description: Amount of cores
  value: "4"
