apiVersion: kubevirt.io/v1alpha1
kind: VM
metadata:
  name: testvm
spec:
  domain:
    devices:
      graphics:
      - autoPort: "yes"
        defaultMode: any
        type: spice
      interfaces:
      - source:
          network: default
        type: network
      video:
      - model:
          type: qxl
      disks:
      - type: network
        snapshot: external
        device: disk
        driver:
          name: qemu
          type: raw
          cache: none
        source:
          host:
            name: iscsi-demo-target
            port: "3260"
          protocol: iscsi
          name: iqn.2017-01.io.kubevirt:sn.42/2
        target:
          dev: vda
      serials:
      - type: pty
        target:
          port: 0
      consoles:
      - type: pty
        target:
          type: serial
          port: 0
    memory:
      unit: MB
      value: 64
    name: testvm
    os:
      type:
        os: hvm
    type: qemu
