apiVersion: kubevirt.io/v1alpha1
kind: VM
metadata:
  name: testvm
spec:
  domain:
    devices:
      graphics:
      - type: spice
      interfaces:
      - mac: 52:54:de:ad:be:ef
      video:
      - type: qxl
      disks:
      - snapshot: external
        device: disk
        driver:
          name: qemu
          type: raw
          cache: none
        source:
          iscsi:
            targetPortal: iscsi-demo-target.default:3260
            iqn: iqn.2017-01.io.kubevirt:sn.42
	    lun: 2
        target:
          dev: vda
      consoles:
      - target:
          port: 0
    memory:
      value: 64
    os:
      type:
        os: hvm
    type: qemu
