apiVersion: kubevirt.io/v1alpha1
kind: VMConfig
metadata:
  name: testvmconfig
spec:
  template:
    features:
        os: linux
    spec:
      domain:
        devices:
          graphics:
          - type: spice
          interfaces:
          - type: network
            source:
              network: default
          video:
          - type: qxl
          consoles:
          - type: pty
        memory:
          unit: MB
          value: 64
        type: qemu
