apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sriov
resources:
- sriov-ns.yaml
- sriov-cni-daemonset.yaml
- sriovdp-daemonset.yaml
- sriovdp-config.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: DaemonSet
    name: kube-sriov-cni-ds-amd64
  path: patch-node-selector.yaml
- target:
    group: apps
    version: v1
    kind: DaemonSet
    name: kube-sriov-device-plugin-amd64
  path: patch-node-selector.yaml
- target:
    group: apps
    version: v1
    kind: DaemonSet
    name: kube-sriov-device-plugin-amd64
  path: patch-sriovdp-resource-prefix.yaml
