load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "addvolume.go",
        "dummy.go",
        "evacuate.go",
        "expandspec.go",
        "memorydump.go",
        "migrate.go",
        "objectgraph.go",
        "portforward.go",
        "removememorydump.go",
        "removevolume.go",
        "restart.go",
        "start.go",
        "stop.go",
        "storage.go",
    ],
    importpath = "kubevirt.io/kubevirt/pkg/virt-api/apiserver/storage/virtualmachine",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/instancetype/expand:go_default_library",
        "//pkg/instancetype/find:go_default_library",
        "//pkg/instancetype/preference/find:go_default_library",
        "//pkg/virt-api/apiserver/storage/virtualmachine/lifecycle:go_default_library",
        "//pkg/virt-api/apiserver/storage/volumes:go_default_library",
        "//pkg/virt-api/rest:go_default_library",
        "//pkg/virt-api/streaming:go_default_library",
        "//pkg/virt-config:go_default_library",
        "//staging/src/kubevirt.io/api/core/v1:go_default_library",
        "//staging/src/kubevirt.io/client-go/kubecli:go_default_library",
        "//vendor/k8s.io/apimachinery/pkg/api/errors:go_default_library",
        "//vendor/k8s.io/apimachinery/pkg/apis/meta/v1:go_default_library",
        "//vendor/k8s.io/apimachinery/pkg/runtime:go_default_library",
        "//vendor/k8s.io/apimachinery/pkg/runtime/schema:go_default_library",
        "//vendor/k8s.io/apimachinery/pkg/util/yaml:go_default_library",
        "//vendor/k8s.io/apiserver/pkg/endpoints/request:go_default_library",
        "//vendor/k8s.io/apiserver/pkg/registry/rest:go_default_library",
    ],
)
