apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sriov
resources:
- sriov-ns.yaml
- sriov-cni-daemonset.yaml
- sriovdp-daemonset.yaml
- sriovdp-config.yaml
images:
  - name: nfvpe/sriov-device-plugin
    newName: quay.io/kubevirtci/sriov-device-plugin
    newTag: v3.3
  - name: nfvpe/sriov-cni
    newName: quay.io/kubevirtci/sriov-cni
    newTag: v2.6
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: DaemonSet
    name: kube-sriov-cni-ds-amd64
  path: patch-node-selector.yaml
- target:
    group: apps
    version: v1
    kind: DaemonSet
    name: kube-sriov-device-plugin-amd64
  path: patch-node-selector.yaml
- target:
    group: apps
    version: v1
    kind: DaemonSet
    name: kube-sriov-device-plugin-amd64
  path: patch-sriovdp-resource-prefix.yaml
