ARG UPGRADE_VERSION=100.0.0
# could not use "FROM golang:1.11" because dep is also needed
FROM fedora:30 AS builder
ARG UPGRADE_VERSION
ENV GOPATH=/go
RUN echo "UPGRADE_VERSION: ${UPGRADE_VERSION}"
WORKDIR /go/src/github.com/kubevirt/hyperconverged-cluster-operator/
COPY . .
RUN dnf install -y dep golang make findutils tar
RUN export UPGRADE_VERSION=${UPGRADE_VERSION}; ./hack/upgrade-create-new-version.sh

FROM quay.io/openshift/origin-operator-registry:latest
ARG KUBEVIRT_PROVIDER
ARG UPGRADE_VERSION
USER 1001
# sed fails if chown=1001 is not applied
COPY --chown=1001 --from=builder /go/src/github.com/kubevirt/hyperconverged-cluster-operator/deploy/olm-catalog /registry

RUN echo "UPGRADE_VERSION: ${UPGRADE_VERSION}"
RUN if [ -n "$KUBEVIRT_PROVIDER" ]; then sed -i "s|quay.io/kubevirt/hyperconverged-cluster-operator:latest|registry:5000/kubevirt/hyperconverged-cluster-operator:latest|g" /registry/kubevirt-hyperconverged/${UPGRADE_VERSION}/kubevirt-hyperconverged-operator.v${UPGRADE_VERSION}.clusterserviceversion.yaml; else sed -i "s|quay.io/kubevirt/hyperconverged-cluster-operator:latest|registry.svc.ci.openshift.org/${OPENSHIFT_BUILD_NAMESPACE}/stable:hyperconverged-cluster-operator|g" /registry/kubevirt-hyperconverged/${UPGRADE_VERSION}/kubevirt-hyperconverged-operator.v${UPGRADE_VERSION}.clusterserviceversion.yaml; fi
RUN cat /registry/kubevirt-hyperconverged/kubevirt-hyperconverged.package.yaml

# Initialize the database
RUN initializer --manifests /registry/kubevirt-hyperconverged --output bundles.db

# There are multiple binaries in the origin-operator-registry
# We want the registry-server
ENTRYPOINT ["registry-server"]
CMD ["--database", "bundles.db"]
