FROM quay.io/openshift/origin-operator-registry:latest
ARG KUBEVIRT_PROVIDER
ARG HCO_VERSION
COPY --from=builder /go/src/github.com/kubevirt/hyperconverged-cluster-operator/deploy/olm-catalog /registry
USER root

# enable KVM_EMULATION for CI, needed by kubevirt-node-labeller on AWS
RUN find /registry/kubevirt-hyperconverged/ -type f -exec sed -E -i 's|^(\s*)- name: KVM_EMULATION$|\1- name: KVM_EMULATION\n\1  value: "true"|' {} \; || :

RUN echo "HCO_VERSION: ${HCO_VERSION}"
RUN if [ -n "$KUBEVIRT_PROVIDER" ]; then sed -i "s|quay.io/kubevirt/hyperconverged-cluster-operator:.*$|registry:5000/kubevirt/hyperconverged-cluster-operator:latest|g" /registry/kubevirt-hyperconverged/${HCO_VERSION}/kubevirt-hyperconverged-operator.v${HCO_VERSION}.clusterserviceversion.yaml; else sed -i "s|quay.io/kubevirt/hyperconverged-cluster-operator:.*$|default-route-openshift-image-registry.apps.build01.ci.devcluster.openshift.com/${OPENSHIFT_BUILD_NAMESPACE}/stable:hyperconverged-cluster-operator|g" /registry/kubevirt-hyperconverged/${HCO_VERSION}/kubevirt-hyperconverged-operator.v${HCO_VERSION}.clusterserviceversion.yaml; fi
RUN cat /registry/kubevirt-hyperconverged/kubevirt-hyperconverged.package.yaml

# Initialize the database
RUN initializer --manifests /registry/kubevirt-hyperconverged --output bundles.db

# There are multiple binaries in the origin-operator-registry
# We want the registry-server
ENTRYPOINT ["registry-server"]
CMD ["--database", "bundles.db"]
