//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
This file is part of the KubeVirt project

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Copyright The KubeVirt Authors.
*/

// Code generated by openapi-gen. DO NOT EDIT.

package v1beta1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CPUInstancetype) OpenAPIModelName() string {
	return "io.kubevirt.api.instancetype.v1beta1.CPUInstancetype"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CPUPreferenceRequirement) OpenAPIModelName() string {
	return "io.kubevirt.api.instancetype.v1beta1.CPUPreferenceRequirement"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CPUPreferences) OpenAPIModelName() string {
	return "io.kubevirt.api.instancetype.v1beta1.CPUPreferences"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ClockPreferences) OpenAPIModelName() string {
	return "io.kubevirt.api.instancetype.v1beta1.ClockPreferences"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in DevicePreferences) OpenAPIModelName() string {
	return "io.kubevirt.api.instancetype.v1beta1.DevicePreferences"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in FeaturePreferences) OpenAPIModelName() string {
	return "io.kubevirt.api.instancetype.v1beta1.FeaturePreferences"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in FirmwarePreferences) OpenAPIModelName() string {
	return "io.kubevirt.api.instancetype.v1beta1.FirmwarePreferences"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MachinePreferences) OpenAPIModelName() string {
	return "io.kubevirt.api.instancetype.v1beta1.MachinePreferences"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MemoryInstancetype) OpenAPIModelName() string {
	return "io.kubevirt.api.instancetype.v1beta1.MemoryInstancetype"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MemoryPreferenceRequirement) OpenAPIModelName() string {
	return "io.kubevirt.api.instancetype.v1beta1.MemoryPreferenceRequirement"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PreferenceRequirements) OpenAPIModelName() string {
	return "io.kubevirt.api.instancetype.v1beta1.PreferenceRequirements"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SpreadOptions) OpenAPIModelName() string {
	return "io.kubevirt.api.instancetype.v1beta1.SpreadOptions"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VirtualMachineClusterInstancetype) OpenAPIModelName() string {
	return "io.kubevirt.api.instancetype.v1beta1.VirtualMachineClusterInstancetype"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VirtualMachineClusterInstancetypeList) OpenAPIModelName() string {
	return "io.kubevirt.api.instancetype.v1beta1.VirtualMachineClusterInstancetypeList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VirtualMachineClusterPreference) OpenAPIModelName() string {
	return "io.kubevirt.api.instancetype.v1beta1.VirtualMachineClusterPreference"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VirtualMachineClusterPreferenceList) OpenAPIModelName() string {
	return "io.kubevirt.api.instancetype.v1beta1.VirtualMachineClusterPreferenceList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VirtualMachineInstancetype) OpenAPIModelName() string {
	return "io.kubevirt.api.instancetype.v1beta1.VirtualMachineInstancetype"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VirtualMachineInstancetypeList) OpenAPIModelName() string {
	return "io.kubevirt.api.instancetype.v1beta1.VirtualMachineInstancetypeList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VirtualMachineInstancetypeSpec) OpenAPIModelName() string {
	return "io.kubevirt.api.instancetype.v1beta1.VirtualMachineInstancetypeSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VirtualMachinePreference) OpenAPIModelName() string {
	return "io.kubevirt.api.instancetype.v1beta1.VirtualMachinePreference"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VirtualMachinePreferenceList) OpenAPIModelName() string {
	return "io.kubevirt.api.instancetype.v1beta1.VirtualMachinePreferenceList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VirtualMachinePreferenceSpec) OpenAPIModelName() string {
	return "io.kubevirt.api.instancetype.v1beta1.VirtualMachinePreferenceSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VolumePreferences) OpenAPIModelName() string {
	return "io.kubevirt.api.instancetype.v1beta1.VolumePreferences"
}
