/*
Copyright The KubeVirt Authors.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1"
	gentype "k8s.io/client-go/gentype"
	monitoringv1 "kubevirt.io/client-go/prometheusoperator/typed/monitoring/v1"
)

// fakeProbes implements ProbeInterface
type fakeProbes struct {
	*gentype.FakeClientWithList[*v1.Probe, *v1.ProbeList]
	Fake *FakeMonitoringV1
}

func newFakeProbes(fake *FakeMonitoringV1, namespace string) monitoringv1.ProbeInterface {
	return &fakeProbes{
		gentype.NewFakeClientWithList[*v1.Probe, *v1.ProbeList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("probes"),
			v1.SchemeGroupVersion.WithKind("Probe"),
			func() *v1.Probe { return &v1.Probe{} },
			func() *v1.ProbeList { return &v1.ProbeList{} },
			func(dst, src *v1.ProbeList) { dst.ListMeta = src.ListMeta },
			func(list *v1.ProbeList) []*v1.Probe { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.ProbeList, items []*v1.Probe) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
