#!/bin/bash
set -e

if [ "$2" != "release" ] || [ "$3" != "end" ] || [ "$4" != "migrated" ]; then
	exit
fi
if [ -d "/run/kubevirt-private/backend-storage-meta" ]; then
	touch /run/kubevirt-private/backend-storage-meta/migrated
fi
