/*
This file is part of the KubeVirt project

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Copyright The KubeVirt Authors.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
	clonev1beta1 "kubevirt.io/api/clone/v1beta1"
)

// VirtualMachineCloneSpecApplyConfiguration represents a declarative configuration of the VirtualMachineCloneSpec type for use
// with apply.
type VirtualMachineCloneSpecApplyConfiguration struct {
	Source            *v1.TypedLocalObjectReference                         `json:"source,omitempty"`
	Target            *v1.TypedLocalObjectReference                         `json:"target,omitempty"`
	AnnotationFilters []string                                              `json:"annotationFilters,omitempty"`
	LabelFilters      []string                                              `json:"labelFilters,omitempty"`
	Template          *VirtualMachineCloneTemplateFiltersApplyConfiguration `json:"template,omitempty"`
	NewMacAddresses   map[string]string                                     `json:"newMacAddresses,omitempty"`
	NewSMBiosSerial   *string                                               `json:"newSMBiosSerial,omitempty"`
	Patches           []string                                              `json:"patches,omitempty"`
	VolumeNamePolicy  *clonev1beta1.VolumeNamePolicy                        `json:"volumeNamePolicy,omitempty"`
}

// VirtualMachineCloneSpecApplyConfiguration constructs a declarative configuration of the VirtualMachineCloneSpec type for use with
// apply.
func VirtualMachineCloneSpec() *VirtualMachineCloneSpecApplyConfiguration {
	return &VirtualMachineCloneSpecApplyConfiguration{}
}

// WithSource sets the Source field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Source field is set to the value of the last call.
func (b *VirtualMachineCloneSpecApplyConfiguration) WithSource(value v1.TypedLocalObjectReference) *VirtualMachineCloneSpecApplyConfiguration {
	b.Source = &value
	return b
}

// WithTarget sets the Target field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Target field is set to the value of the last call.
func (b *VirtualMachineCloneSpecApplyConfiguration) WithTarget(value v1.TypedLocalObjectReference) *VirtualMachineCloneSpecApplyConfiguration {
	b.Target = &value
	return b
}

// WithAnnotationFilters adds the given value to the AnnotationFilters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AnnotationFilters field.
func (b *VirtualMachineCloneSpecApplyConfiguration) WithAnnotationFilters(values ...string) *VirtualMachineCloneSpecApplyConfiguration {
	for i := range values {
		b.AnnotationFilters = append(b.AnnotationFilters, values[i])
	}
	return b
}

// WithLabelFilters adds the given value to the LabelFilters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the LabelFilters field.
func (b *VirtualMachineCloneSpecApplyConfiguration) WithLabelFilters(values ...string) *VirtualMachineCloneSpecApplyConfiguration {
	for i := range values {
		b.LabelFilters = append(b.LabelFilters, values[i])
	}
	return b
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *VirtualMachineCloneSpecApplyConfiguration) WithTemplate(value *VirtualMachineCloneTemplateFiltersApplyConfiguration) *VirtualMachineCloneSpecApplyConfiguration {
	b.Template = value
	return b
}

// WithNewMacAddresses puts the entries into the NewMacAddresses field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NewMacAddresses field,
// overwriting an existing map entries in NewMacAddresses field with the same key.
func (b *VirtualMachineCloneSpecApplyConfiguration) WithNewMacAddresses(entries map[string]string) *VirtualMachineCloneSpecApplyConfiguration {
	if b.NewMacAddresses == nil && len(entries) > 0 {
		b.NewMacAddresses = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.NewMacAddresses[k] = v
	}
	return b
}

// WithNewSMBiosSerial sets the NewSMBiosSerial field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NewSMBiosSerial field is set to the value of the last call.
func (b *VirtualMachineCloneSpecApplyConfiguration) WithNewSMBiosSerial(value string) *VirtualMachineCloneSpecApplyConfiguration {
	b.NewSMBiosSerial = &value
	return b
}

// WithPatches adds the given value to the Patches field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Patches field.
func (b *VirtualMachineCloneSpecApplyConfiguration) WithPatches(values ...string) *VirtualMachineCloneSpecApplyConfiguration {
	for i := range values {
		b.Patches = append(b.Patches, values[i])
	}
	return b
}

// WithVolumeNamePolicy sets the VolumeNamePolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VolumeNamePolicy field is set to the value of the last call.
func (b *VirtualMachineCloneSpecApplyConfiguration) WithVolumeNamePolicy(value clonev1beta1.VolumeNamePolicy) *VirtualMachineCloneSpecApplyConfiguration {
	b.VolumeNamePolicy = &value
	return b
}
