// Automatically generated by swagger-doc. DO NOT EDIT!

package v1

func (DomainSpec) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (Memory) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (Devices) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (Disk) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (ReadOnly) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (DiskSource) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (DiskTarget) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (DiskDriver) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (DiskSourceHost) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (Serial) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (SerialTarget) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (Console) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (ConsoleTarget) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (Interface) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (LinkState) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (BootOrder) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (MAC) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (Model) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (OS) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (OSType) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (SMBios) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (BootMenu) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (SysInfo) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (Entry) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (Channel) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (ChannelTarget) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (ChannelSource) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (Video) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (Graphics) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (Listen) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (Address) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (Ballooning) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (RandomGenerator) SwaggerDoc() map[string]string {
	return map[string]string{}
}
