// Automatically generated by swagger-doc. DO NOT EDIT!

package v1

func (VM) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (VMList) SwaggerDoc() map[string]string {
	return map[string]string{
		"": "VMList is a list of VMs",
	}
}

func (VMSpec) SwaggerDoc() map[string]string {
	return map[string]string{
		"":             "VMSpec is a description of a VM",
		"nodeSelector": "If labels are specified, only nodes marked with all of these labels are considered when scheduling the VM.",
	}
}

func (VMStatus) SwaggerDoc() map[string]string {
	return map[string]string{
		"": "VMStatus represents information about the status of a VM. Status may trail the actual\nstate of a system.",
	}
}

func (VMCondition) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (Spice) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (SpiceInfo) SwaggerDoc() map[string]string {
	return map[string]string{}
}
