/*
This file is part of the KubeVirt project

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Copyright The KubeVirt Authors.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "kubevirt.io/client-go/applyconfigurations/core/v1"
)

// CPUInstancetypeApplyConfiguration represents a declarative configuration of the CPUInstancetype type for use
// with apply.
type CPUInstancetypeApplyConfiguration struct {
	Guest                 *uint32                        `json:"guest,omitempty"`
	Model                 *string                        `json:"model,omitempty"`
	DedicatedCPUPlacement *bool                          `json:"dedicatedCPUPlacement,omitempty"`
	NUMA                  *v1.NUMAApplyConfiguration     `json:"numa,omitempty"`
	IsolateEmulatorThread *bool                          `json:"isolateEmulatorThread,omitempty"`
	Realtime              *v1.RealtimeApplyConfiguration `json:"realtime,omitempty"`
	MaxSockets            *uint32                        `json:"maxSockets,omitempty"`
}

// CPUInstancetypeApplyConfiguration constructs a declarative configuration of the CPUInstancetype type for use with
// apply.
func CPUInstancetype() *CPUInstancetypeApplyConfiguration {
	return &CPUInstancetypeApplyConfiguration{}
}

// WithGuest sets the Guest field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Guest field is set to the value of the last call.
func (b *CPUInstancetypeApplyConfiguration) WithGuest(value uint32) *CPUInstancetypeApplyConfiguration {
	b.Guest = &value
	return b
}

// WithModel sets the Model field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Model field is set to the value of the last call.
func (b *CPUInstancetypeApplyConfiguration) WithModel(value string) *CPUInstancetypeApplyConfiguration {
	b.Model = &value
	return b
}

// WithDedicatedCPUPlacement sets the DedicatedCPUPlacement field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DedicatedCPUPlacement field is set to the value of the last call.
func (b *CPUInstancetypeApplyConfiguration) WithDedicatedCPUPlacement(value bool) *CPUInstancetypeApplyConfiguration {
	b.DedicatedCPUPlacement = &value
	return b
}

// WithNUMA sets the NUMA field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NUMA field is set to the value of the last call.
func (b *CPUInstancetypeApplyConfiguration) WithNUMA(value *v1.NUMAApplyConfiguration) *CPUInstancetypeApplyConfiguration {
	b.NUMA = value
	return b
}

// WithIsolateEmulatorThread sets the IsolateEmulatorThread field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsolateEmulatorThread field is set to the value of the last call.
func (b *CPUInstancetypeApplyConfiguration) WithIsolateEmulatorThread(value bool) *CPUInstancetypeApplyConfiguration {
	b.IsolateEmulatorThread = &value
	return b
}

// WithRealtime sets the Realtime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Realtime field is set to the value of the last call.
func (b *CPUInstancetypeApplyConfiguration) WithRealtime(value *v1.RealtimeApplyConfiguration) *CPUInstancetypeApplyConfiguration {
	b.Realtime = value
	return b
}

// WithMaxSockets sets the MaxSockets field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxSockets field is set to the value of the last call.
func (b *CPUInstancetypeApplyConfiguration) WithMaxSockets(value uint32) *CPUInstancetypeApplyConfiguration {
	b.MaxSockets = &value
	return b
}
