#!/bin/sh
alias log='echo "[$(date)] "'

ARGS="$@"

if [ -z "$QEMU" ]; then
    QEMU="/usr/bin/qemu-system-x86_64"
fi
if [ -z "$LOG" ]; then
    LOG="/var/log/kubevirt/qemu-kube.log"
fi
if [ ! -w "$LOG" ]; then
    LOG="/dev/null"
fi

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -name)
        VM_NAMESPACE_NAME="$2"
        shift
    ;;
    *)
    ;;
esac
shift
done

if [ -z "$VM_NAMESPACE_NAME" ]; then
    log "Libvirt is asking for qemu capabilities." >> $LOG
    exec $QEMU $ARGS
fi

log "Trying to start VM ${VM_NAMESPACE_NAME}." >> $LOG

CMD="$QEMU $ARGS"

log "cgroup path: $SLICE" >> $LOG
log "cgroups: $CONTROLLERS" >> $LOG

log "$CMD" >> $LOG

set -e
sudo cgclassify -g ${CONTROLLERS}:$SLICE --sticky $$

pid=$$
echo "Launching qemu process with pid $pid" >> $LOG

exec $CMD

