/*
Copyright The KubeVirt Authors.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	instancetypev1beta1 "kubevirt.io/api/instancetype/v1beta1"
	scheme "kubevirt.io/client-go/kubevirt/scheme"
)

// VirtualMachineClusterPreferencesGetter has a method to return a VirtualMachineClusterPreferenceInterface.
// A group's client should implement this interface.
type VirtualMachineClusterPreferencesGetter interface {
	VirtualMachineClusterPreferences() VirtualMachineClusterPreferenceInterface
}

// VirtualMachineClusterPreferenceInterface has methods to work with VirtualMachineClusterPreference resources.
type VirtualMachineClusterPreferenceInterface interface {
	Create(ctx context.Context, virtualMachineClusterPreference *instancetypev1beta1.VirtualMachineClusterPreference, opts v1.CreateOptions) (*instancetypev1beta1.VirtualMachineClusterPreference, error)
	Update(ctx context.Context, virtualMachineClusterPreference *instancetypev1beta1.VirtualMachineClusterPreference, opts v1.UpdateOptions) (*instancetypev1beta1.VirtualMachineClusterPreference, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*instancetypev1beta1.VirtualMachineClusterPreference, error)
	List(ctx context.Context, opts v1.ListOptions) (*instancetypev1beta1.VirtualMachineClusterPreferenceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *instancetypev1beta1.VirtualMachineClusterPreference, err error)
	VirtualMachineClusterPreferenceExpansion
}

// virtualMachineClusterPreferences implements VirtualMachineClusterPreferenceInterface
type virtualMachineClusterPreferences struct {
	*gentype.ClientWithList[*instancetypev1beta1.VirtualMachineClusterPreference, *instancetypev1beta1.VirtualMachineClusterPreferenceList]
}

// newVirtualMachineClusterPreferences returns a VirtualMachineClusterPreferences
func newVirtualMachineClusterPreferences(c *InstancetypeV1beta1Client) *virtualMachineClusterPreferences {
	return &virtualMachineClusterPreferences{
		gentype.NewClientWithList[*instancetypev1beta1.VirtualMachineClusterPreference, *instancetypev1beta1.VirtualMachineClusterPreferenceList](
			"virtualmachineclusterpreferences",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *instancetypev1beta1.VirtualMachineClusterPreference {
				return &instancetypev1beta1.VirtualMachineClusterPreference{}
			},
			func() *instancetypev1beta1.VirtualMachineClusterPreferenceList {
				return &instancetypev1beta1.VirtualMachineClusterPreferenceList{}
			},
		),
	}
}
