---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubevirt.io: ""
    prometheus.kubevirt.io: ""
  name: kubevirt-prometheus-metrics
  namespace: kubevirt
spec:
  ports:
  - name: metrics
    port: 443
    protocol: TCP
    targetPort: metrics
  selector:
    prometheus.kubevirt.io: ""
