---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    kubevirt.io: ""
  name: pxes.kubevirt.io
spec:
  group: kubevirt.io
  names:
    kind: PXE
    plural: pxes
    singular: pxe
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        configs:
          items: {}
          type: array
        kind:
          type: string
        metadata: {}
  version: v1alpha2
