---
apiVersion: scheduling.k8s.io/v1
description: Priority class for VMs which should not be preemptited.
kind: PriorityClass
metadata:
  name: non-preemptible
preemptionPolicy: Never
value: 999999999
