---
apiVersion: resource.k8s.io/v1beta2
kind: ResourceClaimTemplate
metadata:
  name: pgpu-resource-claim-tmpl
spec:
  metadata:
    creationTimestamp: null
  spec:
    devices:
      requests:
      - exactly:
          deviceClassName: gpu.example.com
        name: pgpu
