---
apiVersion: scheduling.k8s.io/v1
description: Priority class for VMs which are allowed to be preemptited.
kind: PriorityClass
metadata:
  name: preemptible
preemptionPolicy: PreemptLowerPriority
value: 1000000
