---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-cirros-sata
  name: vm-cirros-sata
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-cirros-sata
    spec:
      domain:
        devices: {}
        resources:
          requests:
            memory: 128Mi
      terminationGracePeriodSeconds: 0
      volumes:
      - containerDisk:
          image: index.docker.io/kubevirt/cirros-container-disk-demo:mybuild
        name: containerdisk
      - cloudInitNoCloud:
          userData: |
            #!/bin/sh

            echo 'printed from cloud-init userdata'
        name: cloudinitdisk
