---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-windows-clarge-windows
  name: vm-windows-clarge-windows
spec:
  instancetype:
    kind: VirtualMachineInstancetype
    name: clarge
  preference:
    kind: VirtualMachinePreference
    name: windows
  runStrategy: Halted
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-windows-clarge-windows
    spec:
      domain:
        devices:
          disks:
          - disk: {}
            name: pvcdisk
        firmware:
          uuid: 5d307ca9-b3ef-428c-8861-06e72d69f223
        resources: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - name: pvcdisk
        persistentVolumeClaim:
          claimName: disk-windows
