---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-sata
  name: vmi-sata
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: sata
        name: containerdisk
    machine:
      type: ""
    resources:
      requests:
        memory: 4096M
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: registry:5000/kubevirt/cirros-container-disk-demo:devel
    name: containerdisk
