---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-sata
  name: vmi-sata
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: sata
        name: containerdisk
    resources:
      requests:
        memory: 128Mi
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: localhost:49172/cirros-container-disk-demo:devel
    name: containerdisk
