---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-alpine-efi
  name: vmi-alpine-efi
spec:
  domain:
    cpu:
      cores: 1
      sockets: 1
      threads: 1
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
    firmware:
      bootloader:
        efi:
          secureBoot: false
    memory:
      guest: 128Mi
    resources:
      requests:
        memory: 1Gi
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: registry:5000/kubevirt/alpine-container-disk-demo:devel
    name: containerdisk
