---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-sata
  name: vmi-sata
spec:
  domain:
    devices: {}
    resources:
      requests:
        memory: 128Mi
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: index.docker.io/kubevirt/cirros-container-disk-demo:mybuild
    name: containerdisk
