---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: vmi-kernel-boot
spec:
  domain:
    devices: {}
    firmware:
      kernelBoot:
        container:
          image: registry:5000/kubevirt/alpine-ext-kernel-boot-demo:devel
          initrdPath: /boot/initramfs-virt
          kernelPath: /boot/vmlinuz-virt
        kernelArgs: console=ttyS0
    resources:
      requests:
        memory: 1Gi
  terminationGracePeriodSeconds: 0
