---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-secureboot
  name: vmi-secureboot
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
    features:
      acpi: {}
      smm:
        enabled: true
    firmware:
      bootloader:
        efi:
          secureBoot: true
    resources:
      requests:
        memory: 1Gi
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: quay.io/kubevirt/fedora-with-test-tooling-container-disk:devel
    name: containerdisk
