---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstancePreset
metadata:
  name: vmi-preset-small
spec:
  domain:
    devices: {}
    machine:
      type: ""
    resources:
      requests:
        memory: 4096M
  selector:
    matchLabels:
      kubevirt.io/vmPreset: vmi-preset-small
