/*
Copyright The KubeVirt Authors.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"
	v1beta1 "kubevirt.io/api/clone/v1beta1"
	clonev1beta1 "kubevirt.io/client-go/kubevirt/typed/clone/v1beta1"
)

// fakeVirtualMachineClones implements VirtualMachineCloneInterface
type fakeVirtualMachineClones struct {
	*gentype.FakeClientWithList[*v1beta1.VirtualMachineClone, *v1beta1.VirtualMachineCloneList]
	Fake *FakeCloneV1beta1
}

func newFakeVirtualMachineClones(fake *FakeCloneV1beta1, namespace string) clonev1beta1.VirtualMachineCloneInterface {
	return &fakeVirtualMachineClones{
		gentype.NewFakeClientWithList[*v1beta1.VirtualMachineClone, *v1beta1.VirtualMachineCloneList](
			fake.Fake,
			namespace,
			v1beta1.SchemeGroupVersion.WithResource("virtualmachineclones"),
			v1beta1.SchemeGroupVersion.WithKind("VirtualMachineClone"),
			func() *v1beta1.VirtualMachineClone { return &v1beta1.VirtualMachineClone{} },
			func() *v1beta1.VirtualMachineCloneList { return &v1beta1.VirtualMachineCloneList{} },
			func(dst, src *v1beta1.VirtualMachineCloneList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.VirtualMachineCloneList) []*v1beta1.VirtualMachineClone {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta1.VirtualMachineCloneList, items []*v1beta1.VirtualMachineClone) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
