/*
Copyright The KubeVirt Authors.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
	v1beta1 "kubevirt.io/client-go/kubevirt/typed/clone/v1beta1"
)

type FakeCloneV1beta1 struct {
	*testing.Fake
}

func (c *FakeCloneV1beta1) VirtualMachineClones(namespace string) v1beta1.VirtualMachineCloneInterface {
	return newFakeVirtualMachineClones(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeCloneV1beta1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
