{{- if and .Values.hooks.enable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    {{- include "kubevirt-cr.labels" . | nindent 4 }}
  name: {{ printf "%s-wait" (include "kubevirt-cr.fullname" .) }}
  namespace: {{ .Release.Namespace }}
{{- end }}
