// Code generated by swagger-doc. DO NOT EDIT.

package v1alpha1

func (VirtualMachineMigrationResourceQuota) SwaggerDoc() map[string]string {
	return map[string]string{
		"": "VirtualMachineMigrationResourceQuota defines resources that should be reserved for a VMI migration\n\n+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object\n+k8s:openapi-gen=true\n+genclient",
	}
}

func (VirtualMachineMigrationResourceQuotaSpec) SwaggerDoc() map[string]string {
	return map[string]string{
		"additionalMigrationResources": "AdditionalMigrationResources specifies the extra resources needed during virtual machine migration,\nabove the resourceQuota limit. This field helps ensure a successful migration by allowing you to define\nthe additional resources required, such as CPU, memory, and storage.\n+optional",
	}
}

func (VirtualMachineMigrationResourceQuotaStatus) SwaggerDoc() map[string]string {
	return map[string]string{
		"creationTime":                       "+optional\n+nullable",
		"phase":                              "+optional",
		"namespaceLocked":                    "+optional\n+nullable",
		"migrationsToBlockingResourceQuotas": "+optional",
		"originalBlockingResourceQuotas":     "+optional\n+listType=atomic",
		"conditions":                         "+optional\n+listType=atomic",
	}
}

func (Condition) SwaggerDoc() map[string]string {
	return map[string]string{
		"":                   "Condition defines conditions",
		"lastProbeTime":      "+optional\n+nullable",
		"lastTransitionTime": "+optional\n+nullable",
		"reason":             "+optional",
		"message":            "+optional",
	}
}

func (VirtualMachineMigrationResourceQuotaList) SwaggerDoc() map[string]string {
	return map[string]string{
		"":      "VirtualMachineMigrationResourceQuota List is a list of VirtualMachineMigrationResourceQuotas\n\n+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object",
		"items": "+listType=atomic",
	}
}
