FROM registry.svc.ci.openshift.org/ci/kubevirt-builder:30-5.8.1 AS builder
WORKDIR /go/src/github.com/kubevirt.io/kubevirt
COPY . .

ARG PULL_PULL_SHA
ENV KUBEVIRT_RUN_UNNESTED=true \
    PULL_PULL_SHA=$PULL_PULL_SHA

RUN source /etc/profile.d/gimme.sh && \
    export GOPATH="/root/go" && \
    ./hack/ci/build-pr.sh

ENTRYPOINT [ "/entrypoint.sh" ]
CMD ["./hack/ci/test-pr.sh"]
