/*
This file is part of the KubeVirt project

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Copyright The KubeVirt Authors.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// VirtualMachineExportBackupApplyConfiguration represents a declarative configuration of the VirtualMachineExportBackup type for use
// with apply.
type VirtualMachineExportBackupApplyConfiguration struct {
	Name      *string                                                `json:"name,omitempty"`
	Endpoints []VirtualMachineExportBackupEndpointApplyConfiguration `json:"endpoints,omitempty"`
}

// VirtualMachineExportBackupApplyConfiguration constructs a declarative configuration of the VirtualMachineExportBackup type for use with
// apply.
func VirtualMachineExportBackup() *VirtualMachineExportBackupApplyConfiguration {
	return &VirtualMachineExportBackupApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *VirtualMachineExportBackupApplyConfiguration) WithName(value string) *VirtualMachineExportBackupApplyConfiguration {
	b.Name = &value
	return b
}

// WithEndpoints adds the given value to the Endpoints field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Endpoints field.
func (b *VirtualMachineExportBackupApplyConfiguration) WithEndpoints(values ...*VirtualMachineExportBackupEndpointApplyConfiguration) *VirtualMachineExportBackupApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEndpoints")
		}
		b.Endpoints = append(b.Endpoints, *values[i])
	}
	return b
}
