/*
This file is part of the KubeVirt project

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Copyright The KubeVirt Authors.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	exportv1 "kubevirt.io/api/export/v1"
)

// VirtualMachineExportBackupEndpointApplyConfiguration represents a declarative configuration of the VirtualMachineExportBackupEndpoint type for use
// with apply.
type VirtualMachineExportBackupEndpointApplyConfiguration struct {
	Endpoint *exportv1.ExportBackupEndpoint `json:"endpoint,omitempty"`
	Url      *string                        `json:"url,omitempty"`
}

// VirtualMachineExportBackupEndpointApplyConfiguration constructs a declarative configuration of the VirtualMachineExportBackupEndpoint type for use with
// apply.
func VirtualMachineExportBackupEndpoint() *VirtualMachineExportBackupEndpointApplyConfiguration {
	return &VirtualMachineExportBackupEndpointApplyConfiguration{}
}

// WithEndpoint sets the Endpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Endpoint field is set to the value of the last call.
func (b *VirtualMachineExportBackupEndpointApplyConfiguration) WithEndpoint(value exportv1.ExportBackupEndpoint) *VirtualMachineExportBackupEndpointApplyConfiguration {
	b.Endpoint = &value
	return b
}

// WithUrl sets the Url field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Url field is set to the value of the last call.
func (b *VirtualMachineExportBackupEndpointApplyConfiguration) WithUrl(value string) *VirtualMachineExportBackupEndpointApplyConfiguration {
	b.Url = &value
	return b
}
