load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_test")

rust_binary(
    name = "virt-launcher-monitor",
    edition = "2021",
    srcs = ["src/main.rs"],
    visibility = ["//visibility:public"],
    deps = [
        "@crate_index//:caps",
        "@crate_index//:nix",
        "@crate_index//:pico-args",
        "@crate_index//:ureq",
    ],
)

rust_test(
    name = "virt-launcher-monitor-tests",
    crate = ":virt-launcher-monitor",
)
