load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["api.go"],
    importpath = "kubevirt.io/kubevirt/pkg/virt-api",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/certificates/bootstrap:go_default_library",
        "//pkg/controller:go_default_library",
        "//pkg/healthz:go_default_library",
        "//pkg/monitoring/metrics/common/client:go_default_library",
        "//pkg/monitoring/metrics/virt-api:go_default_library",
        "//pkg/monitoring/profiler:go_default_library",
        "//pkg/network/admitter:go_default_library",
        "//pkg/service:go_default_library",
        "//pkg/storage/admitters:go_default_library",
        "//pkg/util/ratelimiter:go_default_library",
        "//pkg/util/tls:go_default_library",
        "//pkg/virt-api/apiserver:go_default_library",
        "//pkg/virt-api/apiserver/cluster/clusterprofiler:go_default_library",
        "//pkg/virt-api/apiserver/cluster/expand:go_default_library",
        "//pkg/virt-api/apiserver/cluster/guestfs:go_default_library",
        "//pkg/virt-api/apiserver/cluster/version:go_default_library",
        "//pkg/virt-api/apiserver/storage/virtualmachine:go_default_library",
        "//pkg/virt-api/apiserver/storage/virtualmachineinstance:go_default_library",
        "//pkg/virt-api/webhooks:go_default_library",
        "//pkg/virt-api/webhooks/mutating-webhook:go_default_library",
        "//pkg/virt-api/webhooks/validating-webhook:go_default_library",
        "//pkg/virt-config:go_default_library",
        "//pkg/virt-operator/resource/generate/components:go_default_library",
        "//staging/src/kubevirt.io/api/core/v1:go_default_library",
        "//staging/src/kubevirt.io/client-go/kubecli:go_default_library",
        "//staging/src/kubevirt.io/client-go/log:go_default_library",
        "//staging/src/kubevirt.io/client-go/util:go_default_library",
        "//vendor/github.com/emicklei/go-restful/v3:go_default_library",
        "//vendor/github.com/prometheus/client_golang/prometheus/promhttp:go_default_library",
        "//vendor/github.com/spf13/pflag:go_default_library",
        "//vendor/k8s.io/apimachinery/pkg/apis/meta/v1:go_default_library",
        "//vendor/k8s.io/apimachinery/pkg/util/validation/field:go_default_library",
        "//vendor/k8s.io/apiserver/pkg/endpoints/request:go_default_library",
        "//vendor/k8s.io/client-go/kubernetes:go_default_library",
        "//vendor/k8s.io/client-go/tools/cache:go_default_library",
        "//vendor/k8s.io/client-go/util/certificate:go_default_library",
        "//vendor/k8s.io/client-go/util/flowcontrol:go_default_library",
        "//vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset:go_default_library",
    ],
)
