/*
Copyright The KubeVirt Authors.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"
	v1alpha1 "kubevirt.io/api/pool/v1alpha1"
	poolv1alpha1 "kubevirt.io/client-go/kubevirt/typed/pool/v1alpha1"
)

// fakeVirtualMachinePools implements VirtualMachinePoolInterface
type fakeVirtualMachinePools struct {
	*gentype.FakeClientWithList[*v1alpha1.VirtualMachinePool, *v1alpha1.VirtualMachinePoolList]
	Fake *FakePoolV1alpha1
}

func newFakeVirtualMachinePools(fake *FakePoolV1alpha1, namespace string) poolv1alpha1.VirtualMachinePoolInterface {
	return &fakeVirtualMachinePools{
		gentype.NewFakeClientWithList[*v1alpha1.VirtualMachinePool, *v1alpha1.VirtualMachinePoolList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("virtualmachinepools"),
			v1alpha1.SchemeGroupVersion.WithKind("VirtualMachinePool"),
			func() *v1alpha1.VirtualMachinePool { return &v1alpha1.VirtualMachinePool{} },
			func() *v1alpha1.VirtualMachinePoolList { return &v1alpha1.VirtualMachinePoolList{} },
			func(dst, src *v1alpha1.VirtualMachinePoolList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.VirtualMachinePoolList) []*v1alpha1.VirtualMachinePool {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.VirtualMachinePoolList, items []*v1alpha1.VirtualMachinePool) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
