#!/bin/sh

ARGS="$@"

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -name)
        VM_NAME="$2"
        shift
    ;;
    *)
    ;;
esac
shift
done

if [ -z "$VM_NAME" ]; then
    exec /usr/bin/qemu-kvm $ARGS
fi

CONTAINER_ID=$( docker ps | awk "/k8s_compute.*virt-launcher-$NAME.*/ { print \$1 }" )

DOCKER="docker"
if [ -n "$QEMU_KUBE_DRY_RUN" ]; then
        DOCKER="echo docker"
fi
$DOCKER exec $CONTAINER_ID /bin/sh -c "nohup qemu-kvm $ARGS >/dev/null 2>&1 &"
