/*
Copyright The KubeVirt Authors.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
	v1beta1 "kubevirt.io/client-go/containerizeddataimporter/typed/upload/v1beta1"
)

type FakeUploadV1beta1 struct {
	*testing.Fake
}

func (c *FakeUploadV1beta1) UploadTokenRequests(namespace string) v1beta1.UploadTokenRequestInterface {
	return newFakeUploadTokenRequests(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeUploadV1beta1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
