// Code generated by swagger-doc. DO NOT EDIT.

package v1alpha1

func (BackupOptions) SwaggerDoc() map[string]string {
	return map[string]string{
		"": "BackupOptions are options used to configure virtual machine backup job",
	}
}
