/*
Copyright The KubeVirt Authors.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	backupv1alpha1 "kubevirt.io/api/backup/v1alpha1"
	scheme "kubevirt.io/client-go/kubevirt/scheme"
)

// VirtualMachineBackupsGetter has a method to return a VirtualMachineBackupInterface.
// A group's client should implement this interface.
type VirtualMachineBackupsGetter interface {
	VirtualMachineBackups(namespace string) VirtualMachineBackupInterface
}

// VirtualMachineBackupInterface has methods to work with VirtualMachineBackup resources.
type VirtualMachineBackupInterface interface {
	Create(ctx context.Context, virtualMachineBackup *backupv1alpha1.VirtualMachineBackup, opts v1.CreateOptions) (*backupv1alpha1.VirtualMachineBackup, error)
	Update(ctx context.Context, virtualMachineBackup *backupv1alpha1.VirtualMachineBackup, opts v1.UpdateOptions) (*backupv1alpha1.VirtualMachineBackup, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, virtualMachineBackup *backupv1alpha1.VirtualMachineBackup, opts v1.UpdateOptions) (*backupv1alpha1.VirtualMachineBackup, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*backupv1alpha1.VirtualMachineBackup, error)
	List(ctx context.Context, opts v1.ListOptions) (*backupv1alpha1.VirtualMachineBackupList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *backupv1alpha1.VirtualMachineBackup, err error)
	VirtualMachineBackupExpansion
}

// virtualMachineBackups implements VirtualMachineBackupInterface
type virtualMachineBackups struct {
	*gentype.ClientWithList[*backupv1alpha1.VirtualMachineBackup, *backupv1alpha1.VirtualMachineBackupList]
}

// newVirtualMachineBackups returns a VirtualMachineBackups
func newVirtualMachineBackups(c *BackupV1alpha1Client, namespace string) *virtualMachineBackups {
	return &virtualMachineBackups{
		gentype.NewClientWithList[*backupv1alpha1.VirtualMachineBackup, *backupv1alpha1.VirtualMachineBackupList](
			"virtualmachinebackups",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *backupv1alpha1.VirtualMachineBackup { return &backupv1alpha1.VirtualMachineBackup{} },
			func() *backupv1alpha1.VirtualMachineBackupList { return &backupv1alpha1.VirtualMachineBackupList{} },
		),
	}
}
