/*
This file is part of the KubeVirt project

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Copyright The KubeVirt Authors.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
)

// ContainerDiskSourceApplyConfiguration represents a declarative configuration of the ContainerDiskSource type for use
// with apply.
type ContainerDiskSourceApplyConfiguration struct {
	Image           *string            `json:"image,omitempty"`
	ImagePullSecret *string            `json:"imagePullSecret,omitempty"`
	Path            *string            `json:"path,omitempty"`
	ImagePullPolicy *corev1.PullPolicy `json:"imagePullPolicy,omitempty"`
}

// ContainerDiskSourceApplyConfiguration constructs a declarative configuration of the ContainerDiskSource type for use with
// apply.
func ContainerDiskSource() *ContainerDiskSourceApplyConfiguration {
	return &ContainerDiskSourceApplyConfiguration{}
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *ContainerDiskSourceApplyConfiguration) WithImage(value string) *ContainerDiskSourceApplyConfiguration {
	b.Image = &value
	return b
}

// WithImagePullSecret sets the ImagePullSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImagePullSecret field is set to the value of the last call.
func (b *ContainerDiskSourceApplyConfiguration) WithImagePullSecret(value string) *ContainerDiskSourceApplyConfiguration {
	b.ImagePullSecret = &value
	return b
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *ContainerDiskSourceApplyConfiguration) WithPath(value string) *ContainerDiskSourceApplyConfiguration {
	b.Path = &value
	return b
}

// WithImagePullPolicy sets the ImagePullPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImagePullPolicy field is set to the value of the last call.
func (b *ContainerDiskSourceApplyConfiguration) WithImagePullPolicy(value corev1.PullPolicy) *ContainerDiskSourceApplyConfiguration {
	b.ImagePullPolicy = &value
	return b
}
