/*
This file is part of the KubeVirt project

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Copyright The KubeVirt Authors.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// DiskDeviceApplyConfiguration represents a declarative configuration of the DiskDevice type for use
// with apply.
type DiskDeviceApplyConfiguration struct {
	Disk  *DiskTargetApplyConfiguration  `json:"disk,omitempty"`
	LUN   *LunTargetApplyConfiguration   `json:"lun,omitempty"`
	CDRom *CDRomTargetApplyConfiguration `json:"cdrom,omitempty"`
}

// DiskDeviceApplyConfiguration constructs a declarative configuration of the DiskDevice type for use with
// apply.
func DiskDevice() *DiskDeviceApplyConfiguration {
	return &DiskDeviceApplyConfiguration{}
}

// WithDisk sets the Disk field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Disk field is set to the value of the last call.
func (b *DiskDeviceApplyConfiguration) WithDisk(value *DiskTargetApplyConfiguration) *DiskDeviceApplyConfiguration {
	b.Disk = value
	return b
}

// WithLUN sets the LUN field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LUN field is set to the value of the last call.
func (b *DiskDeviceApplyConfiguration) WithLUN(value *LunTargetApplyConfiguration) *DiskDeviceApplyConfiguration {
	b.LUN = value
	return b
}

// WithCDRom sets the CDRom field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CDRom field is set to the value of the last call.
func (b *DiskDeviceApplyConfiguration) WithCDRom(value *CDRomTargetApplyConfiguration) *DiskDeviceApplyConfiguration {
	b.CDRom = value
	return b
}
