/*
This file is part of the KubeVirt project

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Copyright The KubeVirt Authors.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// EFIApplyConfiguration represents a declarative configuration of the EFI type for use
// with apply.
type EFIApplyConfiguration struct {
	SecureBoot *bool `json:"secureBoot,omitempty"`
	Persistent *bool `json:"persistent,omitempty"`
}

// EFIApplyConfiguration constructs a declarative configuration of the EFI type for use with
// apply.
func EFI() *EFIApplyConfiguration {
	return &EFIApplyConfiguration{}
}

// WithSecureBoot sets the SecureBoot field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecureBoot field is set to the value of the last call.
func (b *EFIApplyConfiguration) WithSecureBoot(value bool) *EFIApplyConfiguration {
	b.SecureBoot = &value
	return b
}

// WithPersistent sets the Persistent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Persistent field is set to the value of the last call.
func (b *EFIApplyConfiguration) WithPersistent(value bool) *EFIApplyConfiguration {
	b.Persistent = &value
	return b
}
