/*
This file is part of the KubeVirt project

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Copyright The KubeVirt Authors.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// MemoryStatusApplyConfiguration represents a declarative configuration of the MemoryStatus type for use
// with apply.
type MemoryStatusApplyConfiguration struct {
	GuestAtBoot    *resource.Quantity `json:"guestAtBoot,omitempty"`
	GuestCurrent   *resource.Quantity `json:"guestCurrent,omitempty"`
	GuestRequested *resource.Quantity `json:"guestRequested,omitempty"`
	MemoryOverhead *resource.Quantity `json:"memoryOverhead,omitempty"`
}

// MemoryStatusApplyConfiguration constructs a declarative configuration of the MemoryStatus type for use with
// apply.
func MemoryStatus() *MemoryStatusApplyConfiguration {
	return &MemoryStatusApplyConfiguration{}
}

// WithGuestAtBoot sets the GuestAtBoot field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GuestAtBoot field is set to the value of the last call.
func (b *MemoryStatusApplyConfiguration) WithGuestAtBoot(value resource.Quantity) *MemoryStatusApplyConfiguration {
	b.GuestAtBoot = &value
	return b
}

// WithGuestCurrent sets the GuestCurrent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GuestCurrent field is set to the value of the last call.
func (b *MemoryStatusApplyConfiguration) WithGuestCurrent(value resource.Quantity) *MemoryStatusApplyConfiguration {
	b.GuestCurrent = &value
	return b
}

// WithGuestRequested sets the GuestRequested field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GuestRequested field is set to the value of the last call.
func (b *MemoryStatusApplyConfiguration) WithGuestRequested(value resource.Quantity) *MemoryStatusApplyConfiguration {
	b.GuestRequested = &value
	return b
}

// WithMemoryOverhead sets the MemoryOverhead field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MemoryOverhead field is set to the value of the last call.
func (b *MemoryStatusApplyConfiguration) WithMemoryOverhead(value resource.Quantity) *MemoryStatusApplyConfiguration {
	b.MemoryOverhead = &value
	return b
}
