/*
This file is part of the KubeVirt project

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Copyright The KubeVirt Authors.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// MigrationConfigurationApplyConfiguration represents a declarative configuration of the MigrationConfiguration type for use
// with apply.
type MigrationConfigurationApplyConfiguration struct {
	NodeDrainTaintKey                 *string            `json:"nodeDrainTaintKey,omitempty"`
	ParallelOutboundMigrationsPerNode *uint32            `json:"parallelOutboundMigrationsPerNode,omitempty"`
	ParallelMigrationsPerCluster      *uint32            `json:"parallelMigrationsPerCluster,omitempty"`
	AllowAutoConverge                 *bool              `json:"allowAutoConverge,omitempty"`
	BandwidthPerMigration             *resource.Quantity `json:"bandwidthPerMigration,omitempty"`
	CompletionTimeoutPerGiB           *int64             `json:"completionTimeoutPerGiB,omitempty"`
	ProgressTimeout                   *int64             `json:"progressTimeout,omitempty"`
	UtilityVolumesTimeout             *int64             `json:"utilityVolumesTimeout,omitempty"`
	UnsafeMigrationOverride           *bool              `json:"unsafeMigrationOverride,omitempty"`
	AllowPostCopy                     *bool              `json:"allowPostCopy,omitempty"`
	AllowWorkloadDisruption           *bool              `json:"allowWorkloadDisruption,omitempty"`
	DisableTLS                        *bool              `json:"disableTLS,omitempty"`
	Network                           *string            `json:"network,omitempty"`
	MatchSELinuxLevelOnMigration      *bool              `json:"matchSELinuxLevelOnMigration,omitempty"`
}

// MigrationConfigurationApplyConfiguration constructs a declarative configuration of the MigrationConfiguration type for use with
// apply.
func MigrationConfiguration() *MigrationConfigurationApplyConfiguration {
	return &MigrationConfigurationApplyConfiguration{}
}

// WithNodeDrainTaintKey sets the NodeDrainTaintKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeDrainTaintKey field is set to the value of the last call.
func (b *MigrationConfigurationApplyConfiguration) WithNodeDrainTaintKey(value string) *MigrationConfigurationApplyConfiguration {
	b.NodeDrainTaintKey = &value
	return b
}

// WithParallelOutboundMigrationsPerNode sets the ParallelOutboundMigrationsPerNode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ParallelOutboundMigrationsPerNode field is set to the value of the last call.
func (b *MigrationConfigurationApplyConfiguration) WithParallelOutboundMigrationsPerNode(value uint32) *MigrationConfigurationApplyConfiguration {
	b.ParallelOutboundMigrationsPerNode = &value
	return b
}

// WithParallelMigrationsPerCluster sets the ParallelMigrationsPerCluster field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ParallelMigrationsPerCluster field is set to the value of the last call.
func (b *MigrationConfigurationApplyConfiguration) WithParallelMigrationsPerCluster(value uint32) *MigrationConfigurationApplyConfiguration {
	b.ParallelMigrationsPerCluster = &value
	return b
}

// WithAllowAutoConverge sets the AllowAutoConverge field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllowAutoConverge field is set to the value of the last call.
func (b *MigrationConfigurationApplyConfiguration) WithAllowAutoConverge(value bool) *MigrationConfigurationApplyConfiguration {
	b.AllowAutoConverge = &value
	return b
}

// WithBandwidthPerMigration sets the BandwidthPerMigration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BandwidthPerMigration field is set to the value of the last call.
func (b *MigrationConfigurationApplyConfiguration) WithBandwidthPerMigration(value resource.Quantity) *MigrationConfigurationApplyConfiguration {
	b.BandwidthPerMigration = &value
	return b
}

// WithCompletionTimeoutPerGiB sets the CompletionTimeoutPerGiB field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CompletionTimeoutPerGiB field is set to the value of the last call.
func (b *MigrationConfigurationApplyConfiguration) WithCompletionTimeoutPerGiB(value int64) *MigrationConfigurationApplyConfiguration {
	b.CompletionTimeoutPerGiB = &value
	return b
}

// WithProgressTimeout sets the ProgressTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProgressTimeout field is set to the value of the last call.
func (b *MigrationConfigurationApplyConfiguration) WithProgressTimeout(value int64) *MigrationConfigurationApplyConfiguration {
	b.ProgressTimeout = &value
	return b
}

// WithUtilityVolumesTimeout sets the UtilityVolumesTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UtilityVolumesTimeout field is set to the value of the last call.
func (b *MigrationConfigurationApplyConfiguration) WithUtilityVolumesTimeout(value int64) *MigrationConfigurationApplyConfiguration {
	b.UtilityVolumesTimeout = &value
	return b
}

// WithUnsafeMigrationOverride sets the UnsafeMigrationOverride field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UnsafeMigrationOverride field is set to the value of the last call.
func (b *MigrationConfigurationApplyConfiguration) WithUnsafeMigrationOverride(value bool) *MigrationConfigurationApplyConfiguration {
	b.UnsafeMigrationOverride = &value
	return b
}

// WithAllowPostCopy sets the AllowPostCopy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllowPostCopy field is set to the value of the last call.
func (b *MigrationConfigurationApplyConfiguration) WithAllowPostCopy(value bool) *MigrationConfigurationApplyConfiguration {
	b.AllowPostCopy = &value
	return b
}

// WithAllowWorkloadDisruption sets the AllowWorkloadDisruption field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllowWorkloadDisruption field is set to the value of the last call.
func (b *MigrationConfigurationApplyConfiguration) WithAllowWorkloadDisruption(value bool) *MigrationConfigurationApplyConfiguration {
	b.AllowWorkloadDisruption = &value
	return b
}

// WithDisableTLS sets the DisableTLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisableTLS field is set to the value of the last call.
func (b *MigrationConfigurationApplyConfiguration) WithDisableTLS(value bool) *MigrationConfigurationApplyConfiguration {
	b.DisableTLS = &value
	return b
}

// WithNetwork sets the Network field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Network field is set to the value of the last call.
func (b *MigrationConfigurationApplyConfiguration) WithNetwork(value string) *MigrationConfigurationApplyConfiguration {
	b.Network = &value
	return b
}

// WithMatchSELinuxLevelOnMigration sets the MatchSELinuxLevelOnMigration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MatchSELinuxLevelOnMigration field is set to the value of the last call.
func (b *MigrationConfigurationApplyConfiguration) WithMatchSELinuxLevelOnMigration(value bool) *MigrationConfigurationApplyConfiguration {
	b.MatchSELinuxLevelOnMigration = &value
	return b
}
