/*
This file is part of the KubeVirt project

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Copyright The KubeVirt Authors.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	types "k8s.io/apimachinery/pkg/types"
)

// VirtualMachineInstanceCommonMigrationStateApplyConfiguration represents a declarative configuration of the VirtualMachineInstanceCommonMigrationState type for use
// with apply.
type VirtualMachineInstanceCommonMigrationStateApplyConfiguration struct {
	Node                      *string    `json:"node,omitempty"`
	Pod                       *string    `json:"pod,omitempty"`
	MigrationUID              *types.UID `json:"migrationUID,omitempty"`
	DomainName                *string    `json:"domainName,omitempty"`
	DomainNamespace           *string    `json:"domainNamespace,omitempty"`
	SyncAddress               *string    `json:"syncAddress,omitempty"`
	PersistentStatePVCName    *string    `json:"persistentStatePVCName,omitempty"`
	SelinuxContext            *string    `json:"selinuxContext,omitempty"`
	VirtualMachineInstanceUID *types.UID `json:"virtualMachineInstanceUID,omitempty"`
}

// VirtualMachineInstanceCommonMigrationStateApplyConfiguration constructs a declarative configuration of the VirtualMachineInstanceCommonMigrationState type for use with
// apply.
func VirtualMachineInstanceCommonMigrationState() *VirtualMachineInstanceCommonMigrationStateApplyConfiguration {
	return &VirtualMachineInstanceCommonMigrationStateApplyConfiguration{}
}

// WithNode sets the Node field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Node field is set to the value of the last call.
func (b *VirtualMachineInstanceCommonMigrationStateApplyConfiguration) WithNode(value string) *VirtualMachineInstanceCommonMigrationStateApplyConfiguration {
	b.Node = &value
	return b
}

// WithPod sets the Pod field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Pod field is set to the value of the last call.
func (b *VirtualMachineInstanceCommonMigrationStateApplyConfiguration) WithPod(value string) *VirtualMachineInstanceCommonMigrationStateApplyConfiguration {
	b.Pod = &value
	return b
}

// WithMigrationUID sets the MigrationUID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MigrationUID field is set to the value of the last call.
func (b *VirtualMachineInstanceCommonMigrationStateApplyConfiguration) WithMigrationUID(value types.UID) *VirtualMachineInstanceCommonMigrationStateApplyConfiguration {
	b.MigrationUID = &value
	return b
}

// WithDomainName sets the DomainName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DomainName field is set to the value of the last call.
func (b *VirtualMachineInstanceCommonMigrationStateApplyConfiguration) WithDomainName(value string) *VirtualMachineInstanceCommonMigrationStateApplyConfiguration {
	b.DomainName = &value
	return b
}

// WithDomainNamespace sets the DomainNamespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DomainNamespace field is set to the value of the last call.
func (b *VirtualMachineInstanceCommonMigrationStateApplyConfiguration) WithDomainNamespace(value string) *VirtualMachineInstanceCommonMigrationStateApplyConfiguration {
	b.DomainNamespace = &value
	return b
}

// WithSyncAddress sets the SyncAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SyncAddress field is set to the value of the last call.
func (b *VirtualMachineInstanceCommonMigrationStateApplyConfiguration) WithSyncAddress(value string) *VirtualMachineInstanceCommonMigrationStateApplyConfiguration {
	b.SyncAddress = &value
	return b
}

// WithPersistentStatePVCName sets the PersistentStatePVCName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PersistentStatePVCName field is set to the value of the last call.
func (b *VirtualMachineInstanceCommonMigrationStateApplyConfiguration) WithPersistentStatePVCName(value string) *VirtualMachineInstanceCommonMigrationStateApplyConfiguration {
	b.PersistentStatePVCName = &value
	return b
}

// WithSelinuxContext sets the SelinuxContext field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SelinuxContext field is set to the value of the last call.
func (b *VirtualMachineInstanceCommonMigrationStateApplyConfiguration) WithSelinuxContext(value string) *VirtualMachineInstanceCommonMigrationStateApplyConfiguration {
	b.SelinuxContext = &value
	return b
}

// WithVirtualMachineInstanceUID sets the VirtualMachineInstanceUID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VirtualMachineInstanceUID field is set to the value of the last call.
func (b *VirtualMachineInstanceCommonMigrationStateApplyConfiguration) WithVirtualMachineInstanceUID(value types.UID) *VirtualMachineInstanceCommonMigrationStateApplyConfiguration {
	b.VirtualMachineInstanceUID = &value
	return b
}
