/*
This file is part of the KubeVirt project

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Copyright The KubeVirt Authors.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
)

// VirtualMachineStartFailureApplyConfiguration represents a declarative configuration of the VirtualMachineStartFailure type for use
// with apply.
type VirtualMachineStartFailureApplyConfiguration struct {
	ConsecutiveFailCount *int         `json:"consecutiveFailCount,omitempty"`
	LastFailedVMIUID     *types.UID   `json:"lastFailedVMIUID,omitempty"`
	RetryAfterTimestamp  *metav1.Time `json:"retryAfterTimestamp,omitempty"`
}

// VirtualMachineStartFailureApplyConfiguration constructs a declarative configuration of the VirtualMachineStartFailure type for use with
// apply.
func VirtualMachineStartFailure() *VirtualMachineStartFailureApplyConfiguration {
	return &VirtualMachineStartFailureApplyConfiguration{}
}

// WithConsecutiveFailCount sets the ConsecutiveFailCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConsecutiveFailCount field is set to the value of the last call.
func (b *VirtualMachineStartFailureApplyConfiguration) WithConsecutiveFailCount(value int) *VirtualMachineStartFailureApplyConfiguration {
	b.ConsecutiveFailCount = &value
	return b
}

// WithLastFailedVMIUID sets the LastFailedVMIUID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastFailedVMIUID field is set to the value of the last call.
func (b *VirtualMachineStartFailureApplyConfiguration) WithLastFailedVMIUID(value types.UID) *VirtualMachineStartFailureApplyConfiguration {
	b.LastFailedVMIUID = &value
	return b
}

// WithRetryAfterTimestamp sets the RetryAfterTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetryAfterTimestamp field is set to the value of the last call.
func (b *VirtualMachineStartFailureApplyConfiguration) WithRetryAfterTimestamp(value metav1.Time) *VirtualMachineStartFailureApplyConfiguration {
	b.RetryAfterTimestamp = &value
	return b
}
