/*
This file is part of the KubeVirt project

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Copyright The KubeVirt Authors.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// VirtualMachineInstanceMigrationSourceApplyConfiguration represents a declarative configuration of the VirtualMachineInstanceMigrationSource type for use
// with apply.
type VirtualMachineInstanceMigrationSourceApplyConfiguration struct {
	MigrationID *string `json:"migrationID,omitempty"`
	ConnectURL  *string `json:"connectURL,omitempty"`
}

// VirtualMachineInstanceMigrationSourceApplyConfiguration constructs a declarative configuration of the VirtualMachineInstanceMigrationSource type for use with
// apply.
func VirtualMachineInstanceMigrationSource() *VirtualMachineInstanceMigrationSourceApplyConfiguration {
	return &VirtualMachineInstanceMigrationSourceApplyConfiguration{}
}

// WithMigrationID sets the MigrationID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MigrationID field is set to the value of the last call.
func (b *VirtualMachineInstanceMigrationSourceApplyConfiguration) WithMigrationID(value string) *VirtualMachineInstanceMigrationSourceApplyConfiguration {
	b.MigrationID = &value
	return b
}

// WithConnectURL sets the ConnectURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConnectURL field is set to the value of the last call.
func (b *VirtualMachineInstanceMigrationSourceApplyConfiguration) WithConnectURL(value string) *VirtualMachineInstanceMigrationSourceApplyConfiguration {
	b.ConnectURL = &value
	return b
}
