/*
This file is part of the KubeVirt project

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Copyright The KubeVirt Authors.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	corev1 "kubevirt.io/api/core/v1"
)

// VolumeApplyConfiguration represents a declarative configuration of the Volume type for use
// with apply.
type VolumeApplyConfiguration struct {
	Name                           *string `json:"name,omitempty"`
	VolumeSourceApplyConfiguration `json:",inline"`
}

// VolumeApplyConfiguration constructs a declarative configuration of the Volume type for use with
// apply.
func Volume() *VolumeApplyConfiguration {
	return &VolumeApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *VolumeApplyConfiguration) WithName(value string) *VolumeApplyConfiguration {
	b.Name = &value
	return b
}

// WithHostDisk sets the HostDisk field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HostDisk field is set to the value of the last call.
func (b *VolumeApplyConfiguration) WithHostDisk(value *HostDiskApplyConfiguration) *VolumeApplyConfiguration {
	b.VolumeSourceApplyConfiguration.HostDisk = value
	return b
}

// WithPersistentVolumeClaim sets the PersistentVolumeClaim field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PersistentVolumeClaim field is set to the value of the last call.
func (b *VolumeApplyConfiguration) WithPersistentVolumeClaim(value *PersistentVolumeClaimVolumeSourceApplyConfiguration) *VolumeApplyConfiguration {
	b.VolumeSourceApplyConfiguration.PersistentVolumeClaim = value
	return b
}

// WithCloudInitNoCloud sets the CloudInitNoCloud field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudInitNoCloud field is set to the value of the last call.
func (b *VolumeApplyConfiguration) WithCloudInitNoCloud(value *CloudInitNoCloudSourceApplyConfiguration) *VolumeApplyConfiguration {
	b.VolumeSourceApplyConfiguration.CloudInitNoCloud = value
	return b
}

// WithCloudInitConfigDrive sets the CloudInitConfigDrive field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudInitConfigDrive field is set to the value of the last call.
func (b *VolumeApplyConfiguration) WithCloudInitConfigDrive(value *CloudInitConfigDriveSourceApplyConfiguration) *VolumeApplyConfiguration {
	b.VolumeSourceApplyConfiguration.CloudInitConfigDrive = value
	return b
}

// WithSysprep sets the Sysprep field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Sysprep field is set to the value of the last call.
func (b *VolumeApplyConfiguration) WithSysprep(value *SysprepSourceApplyConfiguration) *VolumeApplyConfiguration {
	b.VolumeSourceApplyConfiguration.Sysprep = value
	return b
}

// WithContainerDisk sets the ContainerDisk field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ContainerDisk field is set to the value of the last call.
func (b *VolumeApplyConfiguration) WithContainerDisk(value *ContainerDiskSourceApplyConfiguration) *VolumeApplyConfiguration {
	b.VolumeSourceApplyConfiguration.ContainerDisk = value
	return b
}

// WithEphemeral sets the Ephemeral field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ephemeral field is set to the value of the last call.
func (b *VolumeApplyConfiguration) WithEphemeral(value *EphemeralVolumeSourceApplyConfiguration) *VolumeApplyConfiguration {
	b.VolumeSourceApplyConfiguration.Ephemeral = value
	return b
}

// WithEmptyDisk sets the EmptyDisk field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EmptyDisk field is set to the value of the last call.
func (b *VolumeApplyConfiguration) WithEmptyDisk(value *EmptyDiskSourceApplyConfiguration) *VolumeApplyConfiguration {
	b.VolumeSourceApplyConfiguration.EmptyDisk = value
	return b
}

// WithDataVolume sets the DataVolume field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DataVolume field is set to the value of the last call.
func (b *VolumeApplyConfiguration) WithDataVolume(value *DataVolumeSourceApplyConfiguration) *VolumeApplyConfiguration {
	b.VolumeSourceApplyConfiguration.DataVolume = value
	return b
}

// WithConfigMap sets the ConfigMap field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfigMap field is set to the value of the last call.
func (b *VolumeApplyConfiguration) WithConfigMap(value *ConfigMapVolumeSourceApplyConfiguration) *VolumeApplyConfiguration {
	b.VolumeSourceApplyConfiguration.ConfigMap = value
	return b
}

// WithSecret sets the Secret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Secret field is set to the value of the last call.
func (b *VolumeApplyConfiguration) WithSecret(value *SecretVolumeSourceApplyConfiguration) *VolumeApplyConfiguration {
	b.VolumeSourceApplyConfiguration.Secret = value
	return b
}

// WithDownwardAPI sets the DownwardAPI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DownwardAPI field is set to the value of the last call.
func (b *VolumeApplyConfiguration) WithDownwardAPI(value *DownwardAPIVolumeSourceApplyConfiguration) *VolumeApplyConfiguration {
	b.VolumeSourceApplyConfiguration.DownwardAPI = value
	return b
}

// WithServiceAccount sets the ServiceAccount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceAccount field is set to the value of the last call.
func (b *VolumeApplyConfiguration) WithServiceAccount(value *ServiceAccountVolumeSourceApplyConfiguration) *VolumeApplyConfiguration {
	b.VolumeSourceApplyConfiguration.ServiceAccount = value
	return b
}

// WithDownwardMetrics sets the DownwardMetrics field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DownwardMetrics field is set to the value of the last call.
func (b *VolumeApplyConfiguration) WithDownwardMetrics(value corev1.DownwardMetricsVolumeSource) *VolumeApplyConfiguration {
	b.VolumeSourceApplyConfiguration.DownwardMetrics = &value
	return b
}

// WithMemoryDump sets the MemoryDump field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MemoryDump field is set to the value of the last call.
func (b *VolumeApplyConfiguration) WithMemoryDump(value *MemoryDumpVolumeSourceApplyConfiguration) *VolumeApplyConfiguration {
	b.VolumeSourceApplyConfiguration.MemoryDump = value
	return b
}

// WithContainerPath sets the ContainerPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ContainerPath field is set to the value of the last call.
func (b *VolumeApplyConfiguration) WithContainerPath(value *ContainerPathVolumeSourceApplyConfiguration) *VolumeApplyConfiguration {
	b.VolumeSourceApplyConfiguration.ContainerPath = value
	return b
}
