/*
This file is part of the KubeVirt project

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Copyright The KubeVirt Authors.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// WatchdogApplyConfiguration represents a declarative configuration of the Watchdog type for use
// with apply.
type WatchdogApplyConfiguration struct {
	Name                             *string `json:"name,omitempty"`
	WatchdogDeviceApplyConfiguration `json:",inline"`
}

// WatchdogApplyConfiguration constructs a declarative configuration of the Watchdog type for use with
// apply.
func Watchdog() *WatchdogApplyConfiguration {
	return &WatchdogApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *WatchdogApplyConfiguration) WithName(value string) *WatchdogApplyConfiguration {
	b.Name = &value
	return b
}

// WithI6300ESB sets the I6300ESB field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the I6300ESB field is set to the value of the last call.
func (b *WatchdogApplyConfiguration) WithI6300ESB(value *I6300ESBWatchdogApplyConfiguration) *WatchdogApplyConfiguration {
	b.WatchdogDeviceApplyConfiguration.I6300ESB = value
	return b
}

// WithDiag288 sets the Diag288 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Diag288 field is set to the value of the last call.
func (b *WatchdogApplyConfiguration) WithDiag288(value *Diag288WatchdogApplyConfiguration) *WatchdogApplyConfiguration {
	b.WatchdogDeviceApplyConfiguration.Diag288 = value
	return b
}
