/*
This file is part of the KubeVirt project

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Copyright The KubeVirt Authors.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// VirtualMachineRestoreSpecApplyConfiguration represents a declarative configuration of the VirtualMachineRestoreSpec type for use
// with apply.
type VirtualMachineRestoreSpecApplyConfiguration struct {
	Target                     *v1.TypedLocalObjectReference `json:"target,omitempty"`
	VirtualMachineSnapshotName *string                       `json:"virtualMachineSnapshotName,omitempty"`
	Patches                    []string                      `json:"patches,omitempty"`
}

// VirtualMachineRestoreSpecApplyConfiguration constructs a declarative configuration of the VirtualMachineRestoreSpec type for use with
// apply.
func VirtualMachineRestoreSpec() *VirtualMachineRestoreSpecApplyConfiguration {
	return &VirtualMachineRestoreSpecApplyConfiguration{}
}

// WithTarget sets the Target field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Target field is set to the value of the last call.
func (b *VirtualMachineRestoreSpecApplyConfiguration) WithTarget(value v1.TypedLocalObjectReference) *VirtualMachineRestoreSpecApplyConfiguration {
	b.Target = &value
	return b
}

// WithVirtualMachineSnapshotName sets the VirtualMachineSnapshotName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VirtualMachineSnapshotName field is set to the value of the last call.
func (b *VirtualMachineRestoreSpecApplyConfiguration) WithVirtualMachineSnapshotName(value string) *VirtualMachineRestoreSpecApplyConfiguration {
	b.VirtualMachineSnapshotName = &value
	return b
}

// WithPatches adds the given value to the Patches field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Patches field.
func (b *VirtualMachineRestoreSpecApplyConfiguration) WithPatches(values ...string) *VirtualMachineRestoreSpecApplyConfiguration {
	for i := range values {
		b.Patches = append(b.Patches, values[i])
	}
	return b
}
