@startuml
== Run VM (single host) ==

Engine -> vdsm : runVM(spec)

vdsm -> kubernetes : createPod(domxml)
note right
	vdsm tells kubernetes to
	create a virt-launcher pod
end note

create pod
kubernetes -> pod : schedulePod(pod_spec_w_domxml)
note right
	Kubernetes schedules a pod on
	the cluster (with one host)
end note

create virt_launcher
pod -> virt_launcher

virt_launcher -> libvirtd : define(domxml)
virt_launcher -> libvirtd : wait_lifecycle_event()
note right
	virt_launcher now waits until
	the VM is getting undefined
end note

vdsm -> libvirtd : monitorVM()

@enduml
