@startuml
== 1 - Run VM (single host) ==

Engine -> vdsm : runVM(spec)

vdsm -> kubernetes : createPod(domxml)
note right
	Once vdsm is told to create a VM,
	then instead of spwaning the VM itself,
	vdsm tells kubernetes to
	create a virt-launcher pod
end note

create pod
kubernetes -> pod : schedulePod(pod_spec_w_domxml)
note right
	Kubernetes just schedules a pod on
	the cluster (with one host), one
	container within will start the virt-launcher
end note

create virt_launcher
pod -> virt_launcher

virt_launcher -> libvirtd : define(domxml)
note right
	virt_launcher speaks to libvirtd using
        virsh and defines the vm
end note
virt_launcher -> libvirtd : wait_up()
virt_launcher -> libvirtd : wait_down()
note right
	virt_launcher now waits until
	the VM is getting started and then
        undefined
end note

vdsm -> libvirtd : startVM()

vdsm -> libvirtd : monitorVM()

@enduml
