@startuml
title Stop VM

Engine -> vdsm : runVM(spec)
vdsm -> virt_controller : createVM(spec)

virt_controller -> vm_service : set(vmid, spec)
virt_controller -> kubernetes : createPod(host, vmid)
kubernetes -> pod : create(vmid)

pod -> virt_launcher : Init()
virt_launcher -> vdsm : prepareVm()
note right: Connect storage and network

virt_launcher -> vm_service : get(vmid)
virt_launcher <-- vm_service: return (spec)
virt_launcher -> libvirtd : defineVM(spec)
virt_launcher -> libvirtd : startVM()
libvirtd -> qemu : Init()
virt_launcher -> libvirtd : virsh_event_listen()
vdsm -> libvirtd : monitorVM()
libvirtd --> qemu : monitor
@enduml
