ARG BUILDER_IMAGE=quay.io/kubevirt/builder:2510281240-82d14f4b41
ARG DISTROLESS_BASE_IMAGE=gcr.io/distroless/base-debian12:latest

FROM ${BUILDER_IMAGE} AS builder

ARG BUILD_ARCH=amd64
ARG KUBEVIRT_VERSION

WORKDIR /workspace

COPY . .

RUN source /etc/profile.d/gimme.sh && \
    BIN_NAME=virt-api KUBEVIRT_NO_BAZEL=true hack/build-go.sh install cmd/virt-api

RUN echo "nonroot-user:x:1001:1001:nonroot user:/home/nonroot-user:/sbin/nologin" > /tmp/passwd

FROM ${DISTROLESS_BASE_IMAGE}

ARG BUILD_ARCH=amd64
ARG KUBEVIRT_VERSION

COPY --from=builder /workspace/_out/cmd/virt-api/virt-api /usr/bin/virt-api

COPY --from=builder /workspace/.version /.version

COPY --from=builder --chmod=0644 /tmp/passwd /etc/passwd

USER 1001

ENTRYPOINT ["/usr/bin/virt-api"]
