// Automatically generated by MockGen. DO NOT EDIT!
// Source: vm.go

package services

import (
	gomock "github.com/golang/mock/gomock"
	v1 "k8s.io/api/core/v1"

	v10 "kubevirt.io/kubevirt/pkg/api/v1"
)

// Mock of VMService interface
type MockVMService struct {
	ctrl     *gomock.Controller
	recorder *_MockVMServiceRecorder
}

// Recorder for MockVMService (not exported)
type _MockVMServiceRecorder struct {
	mock *MockVMService
}

func NewMockVMService(ctrl *gomock.Controller) *MockVMService {
	mock := &MockVMService{ctrl: ctrl}
	mock.recorder = &_MockVMServiceRecorder{mock}
	return mock
}

func (_m *MockVMService) EXPECT() *_MockVMServiceRecorder {
	return _m.recorder
}

func (_m *MockVMService) StartVMPod(_param0 *v10.VirtualMachine) error {
	ret := _m.ctrl.Call(_m, "StartVMPod", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockVMServiceRecorder) StartVMPod(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "StartVMPod", arg0)
}

func (_m *MockVMService) DeleteVMPod(_param0 *v10.VirtualMachine) error {
	ret := _m.ctrl.Call(_m, "DeleteVMPod", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockVMServiceRecorder) DeleteVMPod(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteVMPod", arg0)
}

func (_m *MockVMService) GetRunningVMPods(_param0 *v10.VirtualMachine) (*v1.PodList, error) {
	ret := _m.ctrl.Call(_m, "GetRunningVMPods", _param0)
	ret0, _ := ret[0].(*v1.PodList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockVMServiceRecorder) GetRunningVMPods(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetRunningVMPods", arg0)
}

func (_m *MockVMService) FetchVM(namespace string, vmName string) (*v10.VirtualMachine, bool, error) {
	ret := _m.ctrl.Call(_m, "FetchVM", namespace, vmName)
	ret0, _ := ret[0].(*v10.VirtualMachine)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

func (_mr *_MockVMServiceRecorder) FetchVM(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "FetchVM", arg0, arg1)
}

func (_m *MockVMService) PutVm(vm *v10.VirtualMachine) (*v10.VirtualMachine, error) {
	ret := _m.ctrl.Call(_m, "PutVm", vm)
	ret0, _ := ret[0].(*v10.VirtualMachine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockVMServiceRecorder) PutVm(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "PutVm", arg0)
}
