/*
Copyright The KubeVirt Authors.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"
	v1alpha1 "kubevirt.io/api/snapshot/v1alpha1"
	snapshotv1alpha1 "kubevirt.io/client-go/kubevirt/typed/snapshot/v1alpha1"
)

// fakeVirtualMachineRestores implements VirtualMachineRestoreInterface
type fakeVirtualMachineRestores struct {
	*gentype.FakeClientWithList[*v1alpha1.VirtualMachineRestore, *v1alpha1.VirtualMachineRestoreList]
	Fake *FakeSnapshotV1alpha1
}

func newFakeVirtualMachineRestores(fake *FakeSnapshotV1alpha1, namespace string) snapshotv1alpha1.VirtualMachineRestoreInterface {
	return &fakeVirtualMachineRestores{
		gentype.NewFakeClientWithList[*v1alpha1.VirtualMachineRestore, *v1alpha1.VirtualMachineRestoreList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("virtualmachinerestores"),
			v1alpha1.SchemeGroupVersion.WithKind("VirtualMachineRestore"),
			func() *v1alpha1.VirtualMachineRestore { return &v1alpha1.VirtualMachineRestore{} },
			func() *v1alpha1.VirtualMachineRestoreList { return &v1alpha1.VirtualMachineRestoreList{} },
			func(dst, src *v1alpha1.VirtualMachineRestoreList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.VirtualMachineRestoreList) []*v1alpha1.VirtualMachineRestore {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.VirtualMachineRestoreList, items []*v1alpha1.VirtualMachineRestore) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
