load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = ["collector.go"],
    importpath = "kubevirt.io/kubevirt/pkg/coveragecollector",
    visibility = ["//visibility:public"],
)

go_test(
    name = "go_default_test",
    srcs = ["collector_test.go"],
    embed = [":go_default_library"],
)
